### ISSUE TITLE
`import numpy as np` hangs Brython in the console

### ISSUE THREAD

**Issue by p-i-** [brython-dev/brython#1008]
I think the correct behaviour would be to immediately report that `numpy` is not supported.

**Comment by davidkwast** [comment]
not happening with 3.7.0 final release

```Brython 3.7.0 on Netscape 5.0 (Macintosh)
>>> import numpy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
>>> import numpy as np
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
>>> ```

**Comment by PierreQuentel** [comment]
I get the same result, so I close the issue.
