### ISSUE TITLE
`python3 -m brython --modules` raises TypeError during execution

### ISSUE THREAD

**Issue by aalok-sathe** [brython-dev/brython#1010]
I ran the command to create a brython lib from imported modules, but for some reason it throws this error. I'm not sure what's causing it.

```bash
python3 -m brython --modules
Create brython_modules.js with all the modules used by the application
searching brython_stdlib.js...
finding packages...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aalok/.local/lib/python3.5/site-packages/brython.py", line 106, in <module>
    finder.make_brython_modules()
  File "/home/aalok/.local/lib/python3.5/site-packages/list_modules.py", line 224, in make_brython_modules
    path = os.path.join(stdlib_dir, "brython_modules.js")
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

**Comment by PierreQuentel** [comment]
It is likely that you run `python3 -m brython --modules` in a directory which is not the one where you have installed Brython; in this case the program can't find `brython_stdlib.js` and sets the variable `stdlib_dir` to `None`. I will update __list_modules.py__ to raise an exception in this case.
