### ISSUE TITLE
Global reference to not-quite-created object does not result in an error.

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#1016]
The code:

```
class O1():

    def meth(self):
        global o2
        o2.meth()
    
class O2():
    def __init__(self):
        self.o1 = O1()
        self.o1.meth()
        
    def meth(self):
        print("in O2 meth")

o2 = O2()
```
Produces an error in Python 3.5:
```
Traceback (most recent call last):
  File "bry1.py", line 15, in <module>
    o2 = O2()
  File "bry1.py", line 10, in __init__
    self.o1.meth()
  File "bry1.py", line 5, in meth
    o2.meth()
NameError: name 'o2' is not defined
```
But no output in Brython 3.7rc2 (in the online Brython editor page).

**Comment by PierreQuentel** [comment]
Hello Eric,

This seems to work with the latest version 3.7.0. Can you confirm ?

**Comment by tiggerntatie** [comment]
I agree - thank you!!
