### ISSUE TITLE
inconsistent errors when comparing incompatible types with NoneType

### ISSUE THREAD

**Issue by chrisbarber** [brython-dev/brython#1038]
Whereas comparing float and NoneType gives this uncaught javascript error:
```
Brython 3.7.0 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
>>> 0.>None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: <Javascript ReferenceError>: bool is not defined
```
Python gives:
```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.>None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```
On the other hand, brython matches python for int or dict and NoneType:
```
>>> 0>None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'int' and 'NoneType'
```
A few types give an understandable error, but not matching python which always seems to give "not supported between instances of 'x' and 'y'":
```
>>> 'a'>None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unorderable types: 'str' > NoneType()
>>> [] > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unorderable types: list() > NoneType()
```
This is a tuple, not a list:
```
>>> () > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: unorderable types: list() > NoneType()
```
Several more that are consistent with python:
```
>>> {} > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'dict' and 'NoneType'
>>> None > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
>>> (x for x in [1,2,3]) > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'generator' and 'NoneType'
>>> len > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'builtin_function_or_method' and 'NoneType'
```
Again, sane but different than python:
```
>>> class X:
...     pass
... 
>>> X > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '__gt__' not supported between types
```
But an object instance:
```
>>> x> None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'X' and 'NoneType'
```
And here another uncaught javascript error:
```
>>> set() > None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception: <Javascript TypeError>: Cannot read property 'length' of undefined
```

**Comment by PierreQuentel** [comment]
Thanks for the report, I have fixed these bugs, and a few others with other types.
