### ISSUE TITLE
Subclass of float

### ISSUE THREAD

**Issue by tiggerntatie** [brython-dev/brython#1115]
I am playing around with subclassing float, and have arrived at an impasse. Code works in Python 3.5.2 (what I have installed) but fails in Brython 3.7.1:

```
class sffloat(float):
    def __new__(cls, value, sf=None):
        return super().__new__(cls, value)

    def __init__(self, value, sf=None):
        float.__init__(value)
        self.sf = sf

a = sffloat(1.0,2)
b = sffloat(2.0,3)
print(type(a))
print(a*b)
print(a.sf)
print(b.sf)
```
Python 3.5.2 output:

```
<class '__main__.sffloat'>
2.0
2
3
```

Brython 3.7.1 output:

```
Traceback (most recent call last):
  File "http://www.brython.info/tests/editor.html?lang=en/tests_editor", line 42, in <lambda>
    doc['run'].bind('click',lambda *args: editor.run())
  File "http://www.brython.info/tests/editor.py", line 112, in run
    exec(src, ns)
  File "<string>", line 9, in <module>
NameError: <Javascript ReferenceError>: $N is not defined
```

**Comment by tiggerntatie** [comment]
Another example, even simpler, but with different problems:

```
class sffloat(float):
    def __new__(cls, value):
        return super().__new__(cls, value)

    def __init__(self, value):
        float.__init__(value)

a = sffloat(1.0)
b = sffloat(2.0)
print(type(a))
print(a*b)
print(a)
print(b)
```

Python 3.5.2 output:

```
<class '__main__.sffloat'>
2.0
1.0
2.0
```
Python 3.7.1 output:

```
<class '__main__.sffloat'>
nan
nan
nan
```

**Comment by tiggerntatie** [comment]
I realize, upon looking at it, that the original example doesn't make sense as an implementation. Rather than revise it, I have another example that malfunctions:

```
lass sffloat(float):
    def __new__(cls, value, sf=None):
        return super().__new__(cls, value)

    def __init__(self, value, sf=None):
        super().__init__()
        self.sf = sf

a = sffloat(1.0, 2)
b = sffloat(2.0, 3)
print(type(a))
print(a*b)
print(a)
print(a.sf)
```

Python 3.5.2:
```
<class '__main__.sffloat'>
2.0
1.0
2
```

Brython 3.7.1:
```
Traceback (most recent call last):
  File "http://www.brython.info/tests/editor.html?lang=en/tests_editor", line 42, in <lambda>
    doc['run'].bind('click',lambda *args: editor.run())
  File "http://www.brython.info/tests/editor.py", line 112, in run
    exec(src, ns)
  File "<string>", line 9, in <module>
Exception: <Javascript TypeError>: Cannot read property 'valueOf' of undefined
```

**Comment by PierreQuentel** [comment]
Thanks for reporting this issue. I have rewritten the implementation of float subclasses on the model of int subclasses.
