### ISSUE TITLE
Run brython on the commandline via node ?

### ISSUE THREAD

**Issue by stuaxo** [brython-dev/brython#1287]
Is it possible to run brython from the commandline, via nodejs ?

In the longer term I'm thinking of using it this to check compatibility of python libraries by running their unit tests in brython.

From there it should be possible to unit test libraries in CI like travis, so they can add a brython badge to the existing badges for python versions.

**Comment by schmave** [comment]
Yes, to some extent. You can run:

```
node scripts/node_bridge.js <your_python_file>
```

to execute a Python file. It looks like importing modules (even those in the standard library) doesn't work in Node right now, so this probably won't be good enough for your application. Error message are also poor. But it's a start.

**Comment by stuaxo** [comment]
Will output to the console work ?

Any idea what would be involved in getting imports working?

**Comment by schmave** [comment]
Output to the console works. There's some unused/commented-out code in node_bridge.js that implements imports form the standard library. I imagine that it is a few years old and so no longer works. Between that code and the import implementation in www/src/py_import.js you might be able to get it working.

**Comment by stuaxo** [comment]
I'm at work on a windows box, things seemed to have a bit of hiccup:

```
node scripts/node_bridge.js hello.py
undefined:7597
throw exc}
^

Error
    at _b_.SyntaxError.$factory (eval at $make_exc (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1)), <anonymous>:141:337)
    at Object._b_.SyntaxError.$factory (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:7828:12)
    at Object.$B.$SyntaxError (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:7595:25)
    at $B.parser.$_SyntaxError (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:233:4)
    at $B.parser.$tokenize (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:4978:1)
    at Object.$B.py2js (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:5028:1)
    at Object.$B.python_to_js (eval at <anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:38:1), <anonymous>:91:22)
    at execute_python_script (C:\dev\scratch\bry\brython\scripts\node_bridge.js:145:24)
    at Object.<anonymous> (C:\dev\scratch\bry\brython\scripts\node_bridge.js:166:1)
[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m {
  args: [
    [32m'invalid syntax (unknown token [�])'[39m,
    [32m'__main_soln__'[39m,
    [33m1[39m,
    [33m0[39m,
    [32m"��p\u0000r\u0000i\u0000n\u0000t\u0000(\u0000'\u0000h\u0000e\u0000l\u0000l\u0000o\u0000 \u0000w\u0000o\u0000r\u0000l\u0000d\u0000'\u0000)\u0000\r\u0000"[39m,
    __brython__: [33mtrue[39m,
    __class__: {
      __class__: [36m[Object][39m,
      __mro__: [36m[Array][39m,
      [32m'$infos'[39m: [36m[Object][39m,
      [32m'$is_class'[39m: [33mtrue[39m,
      [32m'$native'[39m: [33mtrue[39m,
      __iter__: [36m[Function][39m,
      [32m'$factory'[39m: [36m[Function][39m,
      __dir__: [36m[Function][39m,
      __add__: [36m[Function][39m,
      __contains__: [36m[Function][39m,
      __eq__: [36m[Function][39m,
      __getitem__: [36m[Function][39m,
      __ge__: [36m[Function][39m,
      __gt__: [36m[Function][39m,
      __init__: [36m[Function][39m,
      __le__: [36m[Function][39m,
      __len__: [36m[Function][39m,
      __lt__: [36m[Function][39m,
      __mul__: [36m[Function][39m,
      __new__: [36m[Function][39m,
      __repr__: [36m[Function][39m,
      __setattr__: [36m[Function][39m,
      [32m'$setitem'[39m: [36m[Function][39m,
      __sub__: [36m[Function][39m,
      __truediv__: [36m[Function][39m,
      __floordiv__: [36m[Function][39m,
      __mod__: [36m[Function][39m,
      __pow__: [36m[Function][39m,
      __lshift__: [36m[Function][39m,
      __rshift__: [36m[Function][39m,
      __and__: [36m[Function][39m,
      __xor__: [36m[Function][39m,
      __or__: [36m[Function][39m,
      clear: [36m[Function][39m,
      copy: [36m[Function][39m,
      count: [36m[Function][39m,
      index: [36m[Function][39m,
      pop: [36m[Function][39m,
      sort: [36m[Function][39m,
      __hash__: [36m[Function][39m,
      __module__: [32m'builtins'[39m
    }
  ],
  __class__: {
    __class__: {
      __class__: [36m[Circular][39m,
      __mro__: [36m[Array][39m,
      [32m'$infos'[39m: [36m[Object][39m,
      [32m'$is_class'[39m: [33mtrue[39m,
      [32m'$factory'[39m: [36m[Function][39m,
      __call__: [36m[Function][39m,
      __format__: [36m[Function][39m,
      __getattribute__: [36m[Function][39m,
      __hash__: [36m[Function][39m,
      __init__: [36m[Function][39m,
      __init_subclass__: [36m[Function][39m,
      __instancecheck__: [36m[Function][39m,
      __name__: [36m[Object][39m,
      __new__: [36m[Function][39m,
      __str__: [36m[Function][39m,
      __repr__: [36m[Function][39m,
      __prepare__: [36m[Function][39m,
      __qualname__: [36m[Object][39m,
      mro: [36m[Function][39m,
      __subclasscheck__: [36m[Function][39m,
      __module__: [32m'builtins'[39m
    },
    __mro__: [ [36m[Object][39m, [36m[Object][39m, [36m[Object][39m ],
    [32m'$is_class'[39m: [33mtrue[39m,
    [32m'$infos'[39m: {
      __name__: [32m'SyntaxError'[39m,
      __module__: [32m'builtins'[39m,
      __qualname__: [32m'SyntaxError'[39m
    },
    [32m'$factory'[39m: [Function] { __class__: [36m[Object][39m, __objclass__: [36m[Circular][39m },
    __module__: [32m'builtins'[39m
  },
  [32m'$py_error'[39m: [33mtrue[39m,
  [32m'$stack'[39m: [],
  msg: [32m'invalid syntax (unknown token [�])'[39m,
  __cause__: {
    __class__: {
      [32m'$factory'[39m: [36m[Function][39m,
      [32m'$infos'[39m: [36m[Object][39m,
      __bool__: [36m[Function][39m,
      __class__: [36m[Object][39m,
      __hash__: [36m[Function][39m,
      __mro__: [36m[Array][39m,
      __repr__: [36m[Function][39m,
      __str__: [36m[Function][39m,
      [32m'$is_class'[39m: [33mtrue[39m,
      __setattr__: [36m[Function][39m,
      __gt__: [36m[Function][39m,
      __ge__: [36m[Function][39m,
      __lt__: [36m[Function][39m,
      __le__: [36m[Function][39m,
      __module__: [32m'builtins'[39m
    }
  },
  __context__: {
    __class__: {
      [32m'$factory'[39m: [36m[Function][39m,
      [32m'$infos'[39m: [36m[Object][39m,
      __bool__: [36m[Function][39m,
      __class__: [36m[Object][39m,
      __hash__: [36m[Function][39m,
      __mro__: [36m[Array][39m,
      __repr__: [36m[Function][39m,
      __str__: [36m[Function][39m,
      [32m'$is_class'[39m: [33mtrue[39m,
      __setattr__: [36m[Function][39m,
      __gt__: [36m[Function][39m,
      __ge__: [36m[Function][39m,
      __lt__: [36m[Function][39m,
      __le__: [36m[Function][39m,
      __module__: [32m'builtins'[39m
    }
  },
  __suppress_context__: [33mfalse[39m,
  [32m'$line_info'[39m: [32m'1,__main_soln__'[39m,
  text: [32m"��p\u0000r\u0000i\u0000n\u0000t\u0000(\u0000'\u0000h\u0000e\u0000l\u0000l\u0000o\u0000 \u0000w\u0000o\u0000r\u0000l\u0000d\u0000'\u0000)\u0000\r\u0000"[39m,
  offset: [33m0[39m,
  lineno: [33m1[39m,
  filename: [32m'__main_soln__'[39m
}
```

**Comment by schmave** [comment]
What's in hello.py? Looks like some Python code is failing to compile because of a syntax error.

**Comment by stuaxo** [comment]
Apologies - it just contains `print("hello world")` I think it's some windows characterset madness though.

Once I get home and can try on my sane Linux box I bet everything works.

**Comment by stuaxo** [comment]
Great, that works, cheers :)
