### ISSUE TITLE
run_script - how can I retrive the Python stack traceback in every scenario?

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#1447]
Hello! :-)

I wrote some samples, in which I tried to retrieve the Python stack traceback.

My first question is: How could I retrieve the Python stack traceback when calling `run_script` from JavaScript?
The second is: Why is the following exception raised? "DOMException: An attempt was made to use an object that is not, or is no longer, usable".
Other questions may follow ;-)

Sometimes in a bigger project, `run_script` with `loop` set to `false` does not execute the submitted Python code, but I was not able to reproduce it in a smaller sample.

Thanks in advance.

### Sample 1: run_script in Brython, using format_exec to retrieve last stack traceback.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- Brython -->
        <script src="brython/brython.js"></script>
        <script src="brython/brython_stdlib.js"></script>

        <script type="text/python">
import browser
import traceback
try:
    browser.run_script("raise Exception()", "test_module")
except Exception as e:
    browser.console.error("(Brython) Error:", e)
    browser.console.error("(Brython)", traceback.format_exc())
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

```
(Brython) Error: Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    run_script file:///tmp/brython_run_script/brython/brython.js:5113
    run_script file:///tmp/brython_run_script/brython/brython.js:13692
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:20
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    idb_load file:///tmp/brython_run_script/brython/brython.js:5218
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5232
brython.js:9072:20
(Brython) Traceback (most recent call last):
  File "file:///tmp/brython_run_script/index.html/__main__", line 4, in <module>
    browser.run_script("raise Exception()", "test_module")
  File "file:///tmp/brython_run_script/index.html/test_module", line 1, in <module>
    raise Exception()
Exception: Exception
```

### Sample 2: Using run_script in JavaScript, __main__ is empty, loop parameter is set to false.

Script-tag with id "py_script_1" has `type` attribute set to "text/invalid" so that it is ignored by the `brython` call. I forgot that there is the `ipy_id` option.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- Brython -->
        <script src="brython/brython.js"></script>
        <script src="brython/brython_stdlib.js"></script>

        <script type="text/python">
# empty
        </script>
        <script id="py_script_1" type="text/invalid">
raise Exception()
        </script>
    </head>
        <script type="text/javascript">
function test() {
    var id = "py_script_1",
        src;
    src = document.getElementById(id).innerHTML;
    try {
        console.debug(__BRYTHON__.run_script(src, id, false));
    } catch (e) {
        console.error("(JS) Error:", e);
    }
}
    </script>
    <body onload="brython({debug: 1}); test();">
    </body>
</html>
```

```
Uncaught Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    loop file:///tmp/brython_run_script/brython/brython.js:5308
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5259
```

### Sample 3: Same as above, except that the loop parameter is set to true.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- Brython -->
        <script src="brython/brython.js"></script>
        <script src="brython/brython_stdlib.js"></script>

        <script type="text/python">
# empty
        </script>
        <script id="py_script_1" type="text/invalid">
raise Exception()
        </script>
    </head>
        <script type="text/javascript">
function test() {
    var id = "py_script_1",
        src;
    src = document.getElementById(id).innerHTML;
    try {
        console.debug(__BRYTHON__.run_script(src, id, true));
    } catch (e) {
        console.error("(JS) Error:", e);
    }
}
    </script>
    <body onload="brython({debug: 1}); test();">
    </body>
</html>
```

```
(JS) Error: Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    loop file:///tmp/brython_run_script/brython/brython.js:5308
    run_script file:///tmp/brython_run_script/brython/brython.js:5113
    test file:///tmp/brython_run_script/index.html:22
    onload file:///tmp/brython_run_script/index.html:1
index.html:24:17
```

### Sample 4: run_script is called from Brython and JavaScript, loop parameter is set to false.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- Brython -->
        <script src="brython/brython.js"></script>
        <script src="brython/brython_stdlib.js"></script>

        <script type="text/python">
import browser
import traceback
try:
    browser.run_script("raise Exception()", "test_module")
except Exception as e:
    browser.console.error("(Brython) Error:", e)
    browser.console.error("(Brython)", traceback.format_exc())
        </script>
        <script id="py_script_1" type="text/invalid">
raise Exception()
        </script>
    </head>
        <script type="text/javascript">
function test() {
    var id = "py_script_1",
        src;
    src = document.getElementById(id).innerHTML;
    try {
        console.debug(__BRYTHON__.run_script(src, id, false));
    } catch (e) {
        console.error("(JS) Error:", e);
    }
}
    </script>
    <body onload="brython({debug: 1}); test();">
    </body>
</html>
```

```
(Brython) Error: Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    run_script file:///tmp/brython_run_script/brython/brython.js:5113
    run_script file:///tmp/brython_run_script/brython/brython.js:13692
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:20
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    idb_load file:///tmp/brython_run_script/brython/brython.js:5218
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5232
brython.js:9072:20
(Brython) Traceback (most recent call last):
  File "file:///tmp/brython_run_script/index.html/__main__", line 4, in <module>
    browser.run_script("raise Exception()", "test_module")
  File "file:///tmp/brython_run_script/index.html/py_script_1", line 2, in <module>
    raise Exception()
Exception: Exception
brython.js:9072:20
Uncaught Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    loop file:///tmp/brython_run_script/brython/brython.js:5308
    idb_load file:///tmp/brython_run_script/brython/brython.js:5218
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5232
```

### ​Sample 5: Same as above, except that the loop parameter is set to true.

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!-- Brython -->
        <script src="brython/brython.js"></script>
        <script src="brython/brython_stdlib.js"></script>

        <script type="text/python">
import browser
import traceback
try:
    browser.run_script("raise Exception()", "test_module")
except Exception as e:
    browser.console.error("(Brython) Error:", e)
    browser.console.error("(Brython)", traceback.format_exc())
        </script>
        <script id="py_script_1" type="text/invalid">
raise Exception()
        </script>
    </head>
        <script type="text/javascript">
function test() {
    var id = "py_script_1",
        src;
    src = document.getElementById(id).innerHTML;
    try {
        console.debug(__BRYTHON__.run_script(src, id, true));
    } catch (e) {
        console.error("(JS) Error:", e);
    }
}
    </script>
    <body onload="brython({debug: 1}); test();">
    </body>
</html>
```

```
(JS) Error: DOMException: An attempt was made to use an object that is not, or is no longer, usable index.html:30:17
(Brython) Error: Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    run_script file:///tmp/brython_run_script/brython/brython.js:5113
    run_script file:///tmp/brython_run_script/brython/brython.js:13692
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:20
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5259
brython.js:9072:20
(Brython) Traceback (most recent call last):
  File "file:///tmp/brython_run_script/index.html/__main__", line 4, in <module>
    browser.run_script("raise Exception()", "test_module")
  File "file:///tmp/brython_run_script/index.html/py_script_1", line 2, in <module>
    raise Exception()
Exception: Exception
brython.js:9072:20
Uncaught Error: 
    $factory file:///tmp/brython_run_script/brython/brython.js line 7915 > eval:28
    anonymous file:///tmp/brython_run_script/brython/brython.js line 5301 > Function:13
    loop file:///tmp/brython_run_script/brython/brython.js:5301
    loop file:///tmp/brython_run_script/brython/brython.js:5308
    onsuccess file:///tmp/brython_run_script/brython/brython.js:5259
brython.js line 7915 > eval:28:339
```

**Comment by moepnse** [comment]
What I want in one sentence: in case of an error I want to see the Python stack traceback and the error message in the developer console, when using something like `run_script`.

**Comment by moepnse** [comment]
It is written to `log` instead of `error` and I always filtered for error messages and not log messages - my fault. Isn't it more appropriate to write the error message and Python stack traceback to `error` instead of `log`?

**Comment by PierreQuentel** [comment]
Good idea @moepnse : I have changed the default implementation of `sys.stderr` so that the `write()` method uses `console.error()` instead of `console.log()`. The second commit handles the case when the browser doesn't support `console.error()`.
