### ISSUE TITLE
Is importlib.import_module working?

### ISSUE THREAD

**Issue by iansparks** [brython-dev/brython#1532]
I am hesitant to ask because I already asked one stupid question, but I am struggling with dynamic import using `importlib`.

My project has this structure

```
index.html
+ app
   __init__.py
   counter.py
```

`__init__.py` is empty.

counter.py contains:

```
def counter_func():
    print("CALLED!")
```

index.html is:

```
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="icon" href="data:;base64,iVBORw0KGgo=">
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js"></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.8.10/brython_stdlib.min.js"></script>
    </head>

<body onload="brython(1)">

    <script type="text/python">
import importlib
counter = importlib.import_module('app.counter')
counter.counter_func()
    </script>
</body>

</html>

```

when I run a web server in the directory:

```
$ python -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
```

and visit the page at `http://localhost:8080/index.html` the console shows:

```
brython.js:6308 Traceback (most recent call last):
  File VFS.importlib/_bootstrap.py line 988, in _find_and_load
    return _find_and_load_unlocked(name,import_)
  File VFS.importlib/_bootstrap.py line 958, in _find_and_load_unlocked
    _call_with_frames_removed(import_,parent)
  File VFS.importlib/_bootstrap.py line 224, in _call_with_frames_removed
    return f(*args,**kwds)
  File VFS.importlib/_bootstrap.py line 1011, in _gcd_import
    return _find_and_load(name,_gcd_import)
  File VFS.importlib/_bootstrap.py line 988, in _find_and_load
    return _find_and_load_unlocked(name,import_)
  File VFS.importlib/_bootstrap.py line 970, in _find_and_load_unlocked
    raise ModuleNotFoundError(_ERR_MSG.format(name),name=name)
ModuleNotFoundError: No module named 'app'
$io.write @ brython.js:6308
h @ brython.js:5488
e.handle_error @ brython.js:5382
e.loop @ brython.js:5369
(anonymous) @ brython.js:5280
req.onsuccess @ brython.js:5294
IndexedDB (async)
n @ brython.js:5293
e.loop @ brython.js:5371
e.inImported @ brython.js:5347
e.loop @ brython.js:5371
i.onsuccess @ brython.js:5321
IndexedDB (async)
i.onsuccess @ brython.js:5319
brython.js:5384 Uncaught No module named 'app'
    at _b_.ModuleNotFoundError.$factory (eval at $make_exc (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:276216), <anonymous>:1:211)
    at _find_and_load_unlocked3092 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6345:60)
    at _find_and_load3093 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6439:98)
    at _gcd_import3094 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6536:77)
    at _call_with_frames_removed3040 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:1566:47)
    at _find_and_load_unlocked3092 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6304:85)
    at _find_and_load3093 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6439:98)
    at _gcd_import3094 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:6536:77)
    at import_module2978 (eval at exec_module (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:344217), <anonymous>:415:120)
    at eval (eval at e.loop (https://cdn.jsdelivr.net/npm/brython@3.9.0/brython.min.js:7:167880), <anonymous>:15:103)
```

the server log shows that no import requests were made:

```
$ python -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
127.0.0.1 - - [04/Nov/2020 10:08:07] "GET /index.html HTTP/1.1" 200 -
```

Running the same code from the directory with python command-line works:

```
$ python
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> counter = importlib.import_module('app.counter')
>>> counter.counter_func()
CALLED!
```

and if I change the script block to:

```
    <script type="text/python">
from app import counter
counter.counter_func()
    </script>
```

Then all works as expected. I get "CALLED!" on the web console and I can see the import requests expected being made:

```
(nexus) isparks@T3500:~/projects/bro$ python -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
127.0.0.1 - - [04/Nov/2020 10:12:45] "GET /index.html HTTP/1.1" 200 -
127.0.0.1 - - [04/Nov/2020 10:12:46] code 404, message File not found
127.0.0.1 - - [04/Nov/2020 10:12:46] "GET /app.py?v=1604484766804 HTTP/1.1" 404 -
127.0.0.1 - - [04/Nov/2020 10:12:46] "GET /app/__init__.py?v=1604484766811 HTTP/1.1" 200 -
127.0.0.1 - - [04/Nov/2020 10:12:46] "GET /app/counter.py?v=1604484766819 HTTP/1.1" 200 -
```

So I can get it to work with normal imports but not using importlib for dynamic imports. I was hoping to keep startup time down by using dynamic import of modules only when I needed them.

I also wondered about the port but running on port 80 instead of 8080 makes no difference.

**Comment by PierreQuentel** [comment]
Thanks for the report Ian, I can reproduce the bug. Strangely, it doesn't happen when __`brython_stdlib.js`__ is not loaded. I will look into this.

**Comment by PierreQuentel** [comment]
It was easier to fix than I feared - it was a really stupid bug, so let's say we draw 1-1 ;-)
