### ISSUE TITLE
Errors when using the logging module

### ISSUE THREAD

**Issue by petko10** [brython-dev/brython#1569]
I firstly noticed that logging.basicConfig was failing:
```
Brython 3.9.0 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
>>> import logging
>>> logging.basicConfig(level=logging.INFO)
Traceback (most recent call last):
  File <string>, line 1, in <module>
  File VFS.logging/__init__.py, line 1738, in basicConfig
    _releaseLock()
  File VFS.logging/__init__.py, line 215, in _releaseLock
    _lock.release()
  File VFS._thread.py, line 135, in release
    raise error
RuntimeError: RuntimeError 
```
But there's also a problem with logging with the default basicConfig:
```
>>> import logging
>>> log = logging.getLogger('dsa')
>>> log.critical('test')
Traceback (most recent call last):
  File "VFS.interpreter.py", line 208, in keypress
    _=editor_ns['_']=eval(currentLine,
  File "<string>", line 1, in <module>
  File "VFS.logging/__init__.py", line 1299, in critical
    self._log(CRITICAL,msg,args,**kwargs)
  File "VFS.logging/__init__.py", line 1386, in _log
    self.handle(record)
  File "VFS.logging/__init__.py", line 1396, in handle
    self.callHandlers(record)
  File "VFS.logging/__init__.py", line 1466, in callHandlers
    lastResort.handle(record)
  File "VFS.logging/__init__.py", line 834, in handle
    self.emit(record)
  File "VFS.logging/__init__.py", line 1032, in emit
    msg=self.format(record)
  File "VFS.logging/__init__.py", line 809, in format
    return fmt.format(record)
  File "VFS.logging/__init__.py", line 550, in format
    s=self.formatMessage(record)
  File "VFS.logging/__init__.py", line 519, in formatMessage
    return self._style.format(record)
  File "VFS.logging/__init__.py", line 365, in format
    return self._fmt %record.__dict__
TypeError: format requires a mapping
Logged from file <string>, line 1
```

**Comment by PierreQuentel** [comment]
@petko10 
Thanks for reporting this issue. It made me realize that I had not upgraded the logging package to Python 3.9, I have done it in the commit referenced above. With this change, your examples work as in the CPython console. Can you confirm ?

**Comment by petko10** [comment]
@PierreQuentel I can confirm that the examples I quoted above run ok with the Brython version from the commit you referenced. Thanks for handling the issue!

**Comment by PierreQuentel** [comment]
Cool ! I close the issue then.
