### ISSUE TITLE
math.gamma() in special cases

### ISSUE THREAD

**Issue by clairvoyante** [brython-dev/brython#1594]
CPython 3.9.1 :
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import gamma, inf
>>> gamma(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> gamma(-1.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> gamma(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> gamma(0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>> gamma(inf)
inf
>>> gamma(-inf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
>>>
```
Brython 3.9.1 :
```
Brython 3.9.1 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.50
>>> from math import gamma, inf
>>> gamma(-1)
1.0
>>> gamma(-1.0)
-25653050788007548
>>> gamma(0)
1.0
>>> gamma(0.0)
inf
>>> gamma(inf)
nan
>>> gamma(-inf)
nan
>>> 
```

**Comment by clairvoyante** [comment]
and...
CPython 3.9.1 :
```
Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import gamma
>>> gamma(0+0j)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float
>>>
```
Brython 3.9.1 :
```
Brython 3.9.1 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36 Edg/88.0.705.50
>>> from math import gamma
>>> gamma(0+0j)
nan
>>> 
```
