### ISSUE TITLE
Incorrect line number for traceback involving a lambda function

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1645]
```python
f = lambda: 1/0
f()
```

CPython 3.9 prints this traceback:

```
Traceback (most recent call last):
  File "/Users/evan/brython/tb.py", line 2, in <module>
    f()
  File "/Users/evan/brython/tb.py", line 1, in <lambda>
    f = lambda: 1/0
ZeroDivisionError: division by zero
```

Brython prints:

```
Traceback (most recent call last):
  File https://brython.info/tests/editor.py, line 119, in run
    exec(src, ns)
  File <string>, line 2, in <module>
  File <string>, line 2, in lambda_tnbypz4o_146
ZeroDivisionError: division by zero
```

"line 2, in lambda_tnbypz4o_146" should be line 1. 

Thanks for looking into this!

**Comment by PierreQuentel** [comment]
Thanks Evan ! Error reporting is terribly difficult to get right...
