### ISSUE TITLE
`__getitem__(slice)` and `__delitem__(slice)` are not calling when the class is inherited from the list.

### ISSUE THREAD

**Issue by pylover** [brython-dev/brython#1713]
Consider this code:

```python
# kitchen.py

class Foo(list):
    def __getitem__(self, index):
        raise NotImplementedError()

    def __delitem__(self, index):
        raise NotImplementedError()


f = Foo((1, 2, 3, 4))
print(f[1:3:2])
print(f[::2])
del f[0:1]
print(f)
```

### Brython output (Which expected to raise error)
```python
[2]
[1, 3]
[2, 3, 4] 
```

### CPython
```python
Traceback (most recent call last):
  File "www/kitchen.py", line 32, in <module>
    run()
  File "www/kitchen.py", line 19, in run
    print(f[1:3:2])
  File "www/kitchen.py", line 5, in __getitem__
    raise NotImplementedError()
NotImplementedError
```

**Comment by PierreQuentel** [comment]
Thanks for the report Vahid :-)
