### ISSUE TITLE
Error when doing brython-cli --make_package requests

### ISSUE THREAD

**Issue by Nebulizer1213** [brython-dev/brython#1770]
`Traceback (most recent call last):
  File "C:\Users\fixin\AppData\Local\Programs\Python\Python39\Scripts\brython-cli-script.py", line 33, in <module>
    sys.exit(load_entry_point('brython==3.9.5', 'console_scripts', 'brython-cli')())
  File "c:\users\fixin\appdata\local\programs\python\python39\lib\site-packages\brython\__main__.py", line 163, in main
    make_package.make(package_name, os.getcwd())
  File "c:\users\fixin\appdata\local\programs\python\python39\lib\site-packages\brython\make_package.py", line 94, in make
    tree = ast.parse(f.read())
  File "c:\users\fixin\appdata\local\programs\python\python39\lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    print add_code_to_python_process.run_python_code(3736, "print(20)", connect_debugger_tracing=False)
          ^
SyntaxError: invalid syntax`

**Comment by PierreQuentel** [comment]
Can you check which script has the line
```python
print add_code_to_python_process.run_python_code(3736, "print(20)", connect_debugger_tracing=False)
```

This is Python 2.x syntax and probably not included in the latest release of __`requests`__.

BTW, don't expect this package to work with Brython. It sends requests to arbitrary urls for programs running with CPython, which have access to the IP stack of the operating system; whereas all a browser can do is send requests to the same origin, or to the (rare) sites that support cross-origin requests.
