### ISSUE TITLE
brython exec not working under function or lambda

### ISSUE THREAD

**Issue by importos** [brython-dev/brython#1776]
from browser import window,console
l = "b=4+6"
console.log(l) or exec(l) or console.log(b)
## output is 10
eee = lambda x : console.log(x) or exec(x) or console.log(a)
eee("a=2+2")
# raise Exception 'a' not defined

**Comment by PierreQuentel** [comment]
It is the same in CPython:
```
Python 3.10.0rc1 (tags/v3.10.0rc1:cc115e5, Aug  3 2021, 15:22:01) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> s = "b = 4 + 6"
>>> print(s) or exec(s) or print(b)
b = 4 + 6
10
>>> f = lambda x: print(x) or exec(x) or print(a)
>>> f("a = 2 + 2")
a = 2 + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
NameError: name 'a' is not defined
>>>
```
