### ISSUE TITLE
JS exception while parsing code with @

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1816]
Hi there. I've got another example of a syntax error that causes a JS exception:

```
Brython 3.10.3 on Netscape 5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
>>> @x = 123
Traceback (most recent call last):
Exception: <Javascript TypeError>: Cannot read properties of undefined (reading 'forEach')
```

**Comment by PierreQuentel** [comment]
Thanks once again Evan !

Note that the error message produced by Brython is hopefully more clear than CPython's:

```
Brython 3.10.3 on Netscape 5.0 (Windows)
>>> @x = 123
  File <string>, line 1
    @x = 123
       ^
SyntaxError: cannot assign to decorator
>>> 
```

CPython
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> @x = 123
  File "<stdin>", line 1
    @x = 123
     ^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
>>> @x == 123
...
  File "<stdin>", line 2

    ^
SyntaxError: invalid syntax
>>> @x := 123
...
  File "<stdin>", line 2

    ^
SyntaxError: invalid syntax
>>>
```

The "suggestions" introduced in Python 3.10 are generally helpful, but can be confusing at times.

**Comment by schmave** [comment]
Wonderful, that looks great.

**Comment by PierreQuentel** [comment]
I have opened an [issue](https://bugs.python.org/issue45807) in CPython tracker.
