### ISSUE TITLE
make_release causes an error on non-Windows systems 

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#1829]
```bash
oem.py encodings.oem
Traceback (most recent call last):
  File "/home/richard/git/brython/www/../scripts/make_release.py", line 18, in <module>
    import make_stdlib_list
  File "/home/richard/git/brython/scripts/make_stdlib_list.py", line 135, in <module>
    m = __import__(mod_name)
  File "/usr/local/lib/python3.10/encodings/oem.py", line 6, in <module>
    from codecs import oem_encode, oem_decode
ImportError: cannot import name 'oem_encode' from 'codecs' (/usr/local/lib/python3.10/codecs.py)
```

As can be seen in the comment  - intended: 

> Import them explicitly to cause an ImportError
> on non-Windows systems

https://github.com/python/cpython/blob/main/Lib/encodings/oem.py#L4

Thanks 😊

**Comment by PierreQuentel** [comment]
@moepnse 
The commit referenced above should fix the issue, but I can't test on Linux. Can you confirm and close the issue if it is the case ?

**Comment by moepnse** [comment]
@PierreQuentel 
Yes, your commit fixes this issue. :-)

Unfortunately I get another error: 
```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/richard/git/brython/scripts/make_release.py", line 18, in <module>
    import make_stdlib_list
  File "/home/richard/git/brython/scripts/make_stdlib_list.py", line 70, in <module>
    index = open(os.path.join(doc_folder,lang,'index_static.html'), 'r', encoding="utf-8").read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/www/doc/en/index_static.html'
```

````bash
Brython [3, 10]
CPython (3, 10)
/usr/local/bin
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/usr/local/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/local/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/richard/git/brython/scripts/make_release.py", line 18, in <module>
    import make_stdlib_list
  File "/home/richard/git/brython/scripts/make_stdlib_list.py", line 70, in <module>
    index = open(os.path.join(doc_folder,lang,'index_static.html'), 'r', encoding="utf-8").read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/www/doc/en/index_static.html'
```

**Comment by PierreQuentel** [comment]
This seems related to the way you call __`make_relase.py`__. 

__`make_stdlib_dist.py`__ determines the documentation folder by

```python
doc_folder = os.path.join(os.path.dirname(os.getcwd()), 'www', 'doc')
```

If __`make_realease.py`__ is run by `python make_release.py` the doc folder is found at the correct location. In your case, the script is called indirectly using multiprocessing and the program doesn't seem to set the current directory as these scripts expect.

**Comment by moepnse** [comment]
Let's start from scratch.

Let's say I add a new feature to Brython or try to fix a bug and now want to test it. How do I create a new release and run the tests now?

I thought I had to run make_release.py for that.

**Comment by moepnse** [comment]
That's exactly what I did. `make_dist.py` works, but `make_release.py` gives me the error messages mentioned.

```bash
richard@klendathu:~/git/brython/scripts$ python3.10 make_release.py
````

I'll take a closer look at it tomorrow.
