### ISSUE TITLE
datetime.strptime function incompatibility

### ISSUE THREAD

**Issue by tomazfs** [brython-dev/brython#1845]
**1. Brython parses time data that does not match format**
In Brython console on master:
```python
>>> datetime.strptime('01.02.2020', '%d%m%Y')
datetime.datetime(2020, 2, 1, 0, 0)
>>> datetime.strptime('01/02/2020', '%d%m%Y')
datetime.datetime(2020, 2, 1, 0, 0)
>>> datetime.strptime('01-02-2020', '%d%m%Y')
datetime.datetime(2020, 2, 1, 0, 0)
```
In CPython 3.9.9 console:
```python
>>> datetime.strptime('1.2.2020', '%d%m%Y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1.2.2020' does not match format '%d%m%Y'
>>> datetime.strptime('01/02/2020', '%d%m%Y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '01/02/2020' does not match format '%d%m%Y'
>>> datetime.strptime('01-02-2020', '%d%m%Y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '01-02-2020' does not match format '%d%m%Y'
```
**2. Brython does not parse time data without leading zeros in day/month**
In Brython console on master:
```python
>>> datetime.strptime('3.2.2020', '%d.%m.%Y')
Traceback (most recent call last):
  File <string>, line 1, in <module>
Exception: <Javascript Error>: no match 2 2 2 .
```
In CPython 3.9.9 console:
```python
>>> datetime.strptime('3.2.2020', '%d.%m.%Y')
datetime.datetime(2020, 2, 3, 0, 0)
```
**3. Brython raises Exception instead of ValueError**
In Brython console on master:
```python
>>> datetime.strptime('03/02/2020', '%d.%m.%Y')
Traceback (most recent call last):
  File <string>, line 1, in <module>
Exception: <Javascript Error>: no match 2 / 2 .
```
In CPython 3.9.9 console:
```python
>>> datetime.strptime('03/02/2020', '%d.%m.%Y')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\tficko.PFA\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '03/02/2020' does not match format '%d.%m.%Y'
```

Thanks for looking into it!

**Comment by PierreQuentel** [comment]
Thanks for the detailed and precise bug report @tomazfs !
