### ISSUE TITLE
integer & floating point literals with underscore

### ISSUE THREAD

**Issue by clairvoyante** [brython-dev/brython#1864]
In some cases, Brython accepts invalid literals(maybe imaginary literals also).

integer literals :
- CPython 3.10.0 :
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> _12
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name '_12' is not defined
>>> 1_2
12
>>> 12_
  File "<stdin>", line 1
    12_
      ^
SyntaxError: invalid decimal literal
>>>
```
- Brython 3.10.4 :
```
Brython 3.10.4 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
>>> _12
Traceback (most recent call last):
  File <string>, line 1, in <module>
NameError: name '_12' is not defined
>>> 1_2
12
>>> 12_
12
>>>
```
floating point literals :
- CPython 3.10.0 :
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> _12.34e56
  File "<stdin>", line 1
    _12.34e56
    ^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
>>> 1_2.34e56
1.234e+57
>>> 12_.34e56
  File "<stdin>", line 1
    12_.34e56
      ^
SyntaxError: invalid decimal literal
>>> 12._34e56
  File "<stdin>", line 1
    12._34e56
      ^
SyntaxError: invalid decimal literal
>>> 12.3_4e56
1.234e+57
>>> 12.34_e56
  File "<stdin>", line 1
    12.34_e56
         ^
SyntaxError: invalid decimal literal
>>> 12.34e_56
  File "<stdin>", line 1
    12.34e_56
        ^
SyntaxError: invalid decimal literal
>>> 12.34e5_6
1.234e+57
>>> 12.34e56_
  File "<stdin>", line 1
    12.34e56_
            ^
SyntaxError: invalid decimal literal
>>>
```
- Brython 3.10.4 :
```
Brython 3.10.4 on Netscape 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
>>> _12.34e56
  File <string>, line 1
    _12.34e56
       ^
SyntaxError: invalid syntax
>>> 1_2.34e56
1.234e+57
>>> 12_.34e56
1.234e+57
>>> 12._34e56
  File <string>, line 1
    12._34e56
    ^
SyntaxError: invalid syntax
>>> 12.3_4e56
1.234e+57
>>> 12.34_e56
1.234e+57
>>> 12.34e_56
1.234e+57
>>> 12.34e5_6
1.234e+57
>>> 12.34e56_
1.234e+57
>>>
```

**Comment by clairvoyante** [comment]
In https://docs.python.org/3/reference/lexical_analysis.html#integer-literals :
```
One underscore can occur between digits, and after base specifiers like 0x.
```
So, "12_" is invalid.

**Comment by PierreQuentel** [comment]
Many thanks once again @clairvoyante !
