### ISSUE TITLE
Type annotation of top-level variables causes javascript `TypeError`

### ISSUE THREAD

**Issue by vlanore** [brython-dev/brython#1940]
Hello again !

The following code does not seem to work:

```html
<!doctype html>
<html id="html">

<head>
    <meta charset="utf-8">
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
    <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
    <script type="text/python" defer>
        from typing import Optional
        STATE: Optional[dict] = None
    </script>
</head>

<body id="body" onload="brython({debug:1,pythonpath:['.', 'web/Lib/site-packages']});"></body>
</html>
```

When I run it, I get the following error in my javascript console (in Chrome):
```
js error ["<Javascript TypeError>: Cannot read properties of undefined (reading '__class__')", __brython__: true, __class__: {…}]
brython.js:7278 TypeError: Cannot read properties of undefined (reading '__class__')
    at Object.$B.$setitem (brython.js:5285:20)
    at eval (eval at $B.loop (brython.js:4471:1), <anonymous>:21:4)
    at Object.$B.loop (brython.js:4471:24)
    at $B.run_script (brython.js:4341:17)
    at $B.loop (brython.js:4481:10)
    at IDBRequest.openCursor.onsuccess (brython.js:4426:1)
brython.js:7279 frames_stack [Array(4)]
brython.js:7283 line 2 file http://localhost:8000/#__main__ in __main__
brython.js:7285     STATE: Optional[dict] = None
brython.js:4472 Javascript error TypeError: Cannot read properties of undefined (reading '__class__')
    at Object.$B.$setitem (brython.js:5285:20)
    at eval (eval at $B.loop (brython.js:4471:1), <anonymous>:21:4)
    at Object.$B.loop (brython.js:4471:24)
    at $B.run_script (brython.js:4341:17)
    at $B.loop (brython.js:4481:10)
    at IDBRequest.openCursor.onsuccess (brython.js:4426:1)
brython.js:7152 print stack ok []
brython.js:5359 RuntimeError: TypeError: Cannot read properties of undefined (reading '__class__')
```
I'm not sure how to interpret this kind of error, which doesn't look like a normal python error.

Removing the annotation (`STATE: Optional[dict] = None` -> `STATE = None`) removes the error completely.

Is this a bug or am I doing something wrong?

Again, thank you for your time and for your work on brython!

**Comment by vlanore** [comment]
Update : after more testing it seems the issue is not with `Optional` but with any type annotation on top-level variables.

For example `state:str = ""` at top-level produces the same kind of error.

I'll update the issue title accordingly.

**Comment by PierreQuentel** [comment]
Sorry for not solving this issue very fast, I am working on a new parsing engine that will hopefully fix it.

**Comment by vlanore** [comment]
No problem! This was not a blocking issue on my end (I just removed the type annotation for now).

Glad to know the issue is being worked on 👍
