### ISSUE TITLE
Bug in iteration

### ISSUE THREAD

**Issue by aroberge** [brython-dev/brython#196]
The following code when run with Python generates an error:
```
>>> def a():
...   print(1)
...
>>> def repeat(f, n):
...   for i in range(n):
...     f()
...
>>> repeat(2, a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in repeat
TypeError: 'function' object cannot be interpreted as an integer```

However, the same code does nothing with Brython 3.1.3

**Comment by nichwall** [comment]
Are you sure you didn't mean to use `repeat(a, 2)` instead of `repeat(2, a)`?

**Comment by aroberge** [comment]
Using repeat(2, a) was an intentional mistake - one that is caught by Python (as a TypeError) but not by Brython.
