### ISSUE TITLE
Bugs with SyntaxError and exec

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#2008]
These bugs are on the master branch, and not in 3.10.6.

### Bug 1

Running this code in the web editor:

```python
exec("f(x=1,2)\n\n")
```

prints: 
```
  File <string>, line 3
    
    ^
SyntaxError: positional argument follows keyword argument 
```

The error is actually on line 1.

### Bug 2

Running this code in the web editor:

```python
try:
pass
```

prints:
```
Traceback (most recent call last):
  File http://localhost:8001/tests/editor.html?lang=en#tests_editor, line 29, in lambda_g097b5yg_9
    doc['run'].bind('click',lambda *args: editor.run())
  File http://localhost:8001/tests/editor.py, line 124, in run
    traceback.print_exc(file=sys.stderr)
  File VFS.tb.py, line 43, in print_exc
    file.write(format_exc())
  File VFS.tb.py, line 29, in format_exc
    filename=code.co_filename
AttributeError: type object 'code' has no attribute 'co_filename'
```

From what I can tell, `frame.f_code` is returning an undefined co_filename for the top-level frame.

### Bug 3

Running this code in the web editor:

```python
import traceback
try:
  exec("x=")
except:
  traceback.print_exc()
```

prints: 
```
Traceback (most recent call last):
  File "http://localhost:8001/tests/editor.html?lang=en#tests_editor", line 29, in lambda_g097b5yg_9
    doc['run'].bind('click',lambda *args: editor.run())
  File "http://localhost:8001/tests/editor.py", line 121, in run
    exec(src, ns)
  File "<string>", line 3, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1
    x=
      ^
SyntaxError: invalid syntax
```

For the same code, CPython 3.10 prints:
```
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    exec("x=")
  File "<string>", line 1
    x=
      ^
SyntaxError: invalid syntax
```

Thanks in advance for taking a look at these!

**Comment by PierreQuentel** [comment]
After many changes in the management of execution frames and in exec(), I think these bugs are now fixed. Can you check ?

**Comment by schmave** [comment]
Looks good to me! This is tricky stuff. Thanks for working on it :)
