### ISSUE TITLE
TypeError: init_subclass is not a function

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2057]
Hello,

after trying the latest development snapshot, i got an `classmethod is not callable` error. So i tried to write a small sample to reproduce the error and ended up with this:

```python
class PluginBase:
    @classmethod
    def __init_subclass__(cls, **kwargs):
        print("subclass:", cls)
        super().__init_subclass__(**kwargs)

class Plugin(PluginBase):
    pass
```

```python
Javascript error
 TypeError: init_subclass is not a function
    __new__ file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:5165
    $class_constructor file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:5009
    anonymous file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js line 4726 > Function:124
    loop file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4726
    run_script file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4594
    loop file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4740
    onsuccess file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4681
    onsuccess file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4672
    idb_open file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4657
    loop file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4740
    brython file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js:4578
    onload file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/brython_classmethod_is_not_callable.html:1
brython.js:7655:9
frames 
```

Thank you for your time!

**Comment by moepnse** [comment]
Now I was able to reproduce the former Exception:

```python
class PluginBase:
    @classmethod
    def __init_subclass__(cls, **kwargs):
        print("subclass:", cls)
        super().__init_subclass__(**kwargs)


class Client:
    # this is implicitly a @classmethod
    def __init_subclass__(cls, **kwargs):
        print("subclass:", cls)
        super().__init_subclass__(**kwargs)


class Plugin(Client, PluginBase):
    def __init_subclass__(cls, **kwargs):
        print("subclass:", cls)
        super().__init_subclass__(**kwargs)


class Plugin1(Plugin):
    pass
```

```javascript
subclass: <class '__main__.Plugin'>
[brython.js:5711:56](file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js)
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/brython_classmethod_is_not_callable.html#__main__", line 15, in <module>
    class Plugin(Client, PluginBase):
  File "file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/brython_classmethod_is_not_callable.html#__main__", line 12, in __init_subclass__
    super().__init_subclass__(**kwargs)
TypeError: 'classmethod' object is not callable [brython.js:5711:56](file:///C:/Users/user1/issues/brython_classmethod_is_not_callable/static/brython/brython.js)
```

Thanks!
