### ISSUE TITLE
VFS.importlib._bootstrap_external.py: AttributeError: 'NoneType' object has no attribute 'ModuleSpec'

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2081]
Hello,

sorry to be brief: bellow the Exception and a sample that reproduces the error.

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_bootstrap_external.html#__main__", line 34, in <module>
    load_plugin("plugins/test_plugin.py")
  File "file:///C:/Users/user1/issues/brython_bootstrap_external.html#__main__", line 23, in load_plugin
    spec = importlib.util.spec_from_file_location(module_name, module_path)
  File "VFS.importlib._bootstrap_external.py", line 684, in spec_from_file_location
    spec=_bootstrap.ModuleSpec(name,loader,origin=location)
AttributeError: 'NoneType' object has no attribute 'ModuleSpec' brython.js:5711:56
    flush https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5711
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4843
    show_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7923
    handle_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7927
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4738
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4640
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4654
Uncaught ModuleSpec: 
    $factory https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 7719 > eval:3
    attr_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7746
    __getattribute__ https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    $getattr https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:6707
    spec_from_file_location10303 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9327 > Function:2392
    load_plugin11 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4726 > Function:71
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4726 > Function:131
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4640
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4654
brython.js line 7719 > eval:3:15
    $factory https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 7719 > eval:3
    attr_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7746
    __getattribute__ https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    $getattr https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:6707
    spec_from_file_location10303 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9327 > Function:2392
    load_plugin11 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4726 > Function:71
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4726 > Function:131
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4640
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4654
```

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - AttributeError: 'NoneType' object has no attribute 'ModuleSpec'</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

<script type="text/javascript">
__BRYTHON__.add_files({
    "data/test.txt": {
        "content": "dGVzdA==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    },
    "plugins/test_plugin.py": {
        "content": "aXNfY2xpZW50ID0gVHJ1ZQoKaW1wb3J0IG9zCmltcG9ydCB0cmFjZWJhY2sKZnJvbSBicm93c2VyIGltcG9ydCBkb2N1bWVudCx3aW5kb3csY29uc29sZSxhaW8KaW1wb3J0IGpzb24KCnByaW50KCJIZWxsbyBXb3JsZCEiKQ==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    }})
    </script>

    <script type="text/python">
# Standard library imports.
import sys
from browser import console
import browser.aio
import pathlib
import importlib.util

# Related third party imports.

# Local application/library specific imports.


def load_plugin(module_path, add_to_sys_modules=True):
    stem = pathlib.Path(module_path).stem
    if stem[0].isdigit():
        tmp = stem.split("_", 1)
        if len(tmp) == 2:
            stem = tmp[1]
    module_name =  "ui_plugin_" + stem
    if module_name in sys.modules:
        print("{} already loaded".format(module_name))
        return sys.modules[module_name]
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None:
        raise FileNotFoundError(module_path)
    module = importlib.util.module_from_spec(spec)
    module.is_plugin = True
    if add_to_sys_modules:
        sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


load_plugin("plugins/test_plugin.py")
 

        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

Thanks!

**Comment by moepnse** [comment]
Hey!

It seems that `_bootstrap_external` is not set correctly. 🤔 

The error is gone if I set `_bootstrap_external` manually:

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - AttributeError: 'NoneType' object has no attribute 'ModuleSpec'</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

<script type="text/javascript">
__BRYTHON__.add_files({
    "data/test.txt": {
        "content": "dGVzdA==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    },
    "plugins/test_plugin.py": {
        "content": "aXNfY2xpZW50ID0gVHJ1ZQoKaW1wb3J0IG9zCmltcG9ydCB0cmFjZWJhY2sKZnJvbSBicm93c2VyIGltcG9ydCBkb2N1bWVudCx3aW5kb3csY29uc29sZSxhaW8KaW1wb3J0IGpzb24KCnByaW50KCJIZWxsbyBXb3JsZCEiKQ==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    }})
    </script>

    <script type="text/python">
# Standard library imports.
import sys
from browser import console
import browser.aio
import pathlib
import importlib.util

# vvvv - workaround:
from importlib import _bootstrap
from importlib import _bootstrap_external
_bootstrap_external._set_bootstrap_module(_bootstrap)
_bootstrap._bootstrap_external = _bootstrap_external
# ^^^^

# Related third party imports.

# Local application/library specific imports.


def load_plugin(module_path, add_to_sys_modules=True):
    stem = pathlib.Path(module_path).stem
    if stem[0].isdigit():
        tmp = stem.split("_", 1)
        if len(tmp) == 2:
            stem = tmp[1]
    module_name =  "ui_plugin_" + stem
    if module_name in sys.modules:
        print("{} already loaded".format(module_name))
        return sys.modules[module_name]
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None:
        raise FileNotFoundError(module_path)
    module = importlib.util.module_from_spec(spec)
    module.is_plugin = True
    if add_to_sys_modules:
        sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


load_plugin("plugins/test_plugin.py")
 
import ui_plugin_test_plugin
print(dir(ui_plugin_test_plugin))
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```
