### ISSUE TITLE
importlib issue

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2091]
Hello,

when using the latest development snapshot the following error occurs:

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/brython_import_issue2.html#__main__", line 33, in <module>
    load_plugin("plugins/test_plugin.py")
  File "file:///C:/Users/user1/brython_import_issue2.html#__main__", line 29, in load_plugin
    spec.loader.exec_module(module)
  File "VFS.importlib._bootstrap_external.py", line 936, in exec_module
    code=self.get_code(module.__name__)
  File "VFS.importlib._bootstrap_external.py", line 1073, in get_code
    source_bytes=self.get_data(source_path)
  File "VFS.importlib._bootstrap_external.py", line 1130, in get_data
    with _io.open_code(str(path))as file:
             ^^^^^^^^^^^^^^^^^^^^
  File "VFS._io.py", line 240, in open_code
    return __builtins__.open(file,encoding="utf-8")
FileNotFoundError: cannot use 'open()' with protocol 'file' brython.js:5735:56
Uncaught Error: 
    $factory https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 7754 > eval:55
    $url_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7405
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5726
    open_code6995 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9462 > Function:337
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5727
    get_data10226 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9462 > Function:4524
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    get_code10209 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9462 > Function:4113
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    exec_module10166 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9462 > Function:3452
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    load_plugin11 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4743 > Function:87
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5727
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4743 > Function:129
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4743
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    idb_get https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    inImported https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4726
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4611
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4698
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4689
    idb_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4674
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4757
    brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4595
    onload file:///C:/Users/lambojr/issues/brython_malformed Unicode character escape sequence/brython_import_issue2.html:1
```

Test last working snapshot I tested was 5ed36ec84a1c75c21dd615d44dfacb7346a8ab1b.

The sample bellow reproduces the error:

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - importlib issue</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/javascript">
__BRYTHON__.add_files({
    "data/test.txt": {
        "content": "dGVzdA==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    },
    "plugins/test_plugin.py": {
        "content": "aXNfY2xpZW50ID0gVHJ1ZQoKaW1wb3J0IG9zCmltcG9ydCB0cmFjZWJhY2sKZnJvbSBicm93c2VyIGltcG9ydCBkb2N1bWVudCx3aW5kb3csY29uc29sZSxhaW8KaW1wb3J0IGpzb24KCnByaW50KCJIZWxsbyBXb3JsZCEiKQ==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    }})
        </script>

        <script type="text/python">
# Standard library imports.
import sys
from browser import console
import pathlib
import importlib.util

# Related third party imports.

# Local application/library specific imports.


def load_plugin(module_path, add_to_sys_modules=True):
    stem = pathlib.Path(module_path).stem
    if stem[0].isdigit():
        tmp = stem.split("_", 1)
        if len(tmp) == 2:
            stem = tmp[1]
    module_name =  "ui_plugin_" + stem
    if module_name in sys.modules:
        print("{} already loaded".format(module_name))
        return sys.modules[module_name]
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None:
        raise FileNotFoundError(module_path)
    module = importlib.util.module_from_spec(spec)
    module.is_plugin = True
    if add_to_sys_modules:
        sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


load_plugin("plugins/test_plugin.py")
 

import ui_plugin_test_plugin
print(dir(ui_plugin_test_plugin))
        </script>
    </head>
    <body onload="brython({debug: 1});">
    </body>
</html>
```

Thank you for your time!

**Comment by PierreQuentel** [comment]
It is probably because you have loaded the HTML page with the browser's File / Open menu, instead of running a local web server and entering something like _localhost:8000/page.html_ in the address bar.

**Comment by moepnse** [comment]
It doesn't matter if I use http or the file protocol, both result in a `FileNotFoundError` exception and a request after page load over http or the file protocol is not necessary, because the file is part of the html file and added there to the VFS. There are just three requests: the html file and two JavaScript files: `brython.js` and `brython_stdlib.js`.

```python
Traceback (most recent call last):
  File "http://localhost:8084/brython_import_issue2.html#__main__", line 33, in <module>
    load_plugin("plugins/test_plugin.py")
  File "http://localhost:8084/brython_import_issue2.html#__main__", line 29, in load_plugin
    spec.loader.exec_module(module)
  File "VFS.importlib._bootstrap_external.py", line 936, in exec_module
    code=self.get_code(module.__name__)
  File "VFS.importlib._bootstrap_external.py", line 1073, in get_code
    source_bytes=self.get_data(source_path)
  File "VFS.importlib._bootstrap_external.py", line 1130, in get_data
    with _io.open_code(str(path))as file:
             ^^^^^^^^^^^^^^^^^^^^
  File "VFS._io.py", line 240, in open_code
    return __builtins__.open(file,encoding="utf-8")
FileNotFoundError: https://raw.githack.com/brython-dev/brython/master/www/src/plugins/test_plugin.py [brython.js:5735:56](https://raw.githack.com/brython-dev/brython/master/www/src/brython.js)
    flush https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5735
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    show_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7970
    handle_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7974
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4755
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
Uncaught Error: 
    $factory https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 7754 > eval:55
    onreadystatechange https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7394
    $url_open https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:7405
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5726
    open_code6995 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9375 > Function:338
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5727
    get_data10226 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9375 > Function:4525
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    get_code10209 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9375 > Function:4114
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    exec_module10166 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9375 > Function:3453
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4860
    load_plugin11 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4743 > Function:87
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5727
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4743 > Function:129
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4743
    idb_load https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4657
    onsuccess https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4671
[brython.js line 7754 > eval:55:15](https://raw.githack.com/brython-dev/brython/master/www/src/brython.js%20line%207754%20%3E%20eval)
```

**Comment by PierreQuentel** [comment]
> It doesn't matter if I use http or the file protocol, both result in a FileNotFoundError exception

Sorry, I should have tested before...

The problem here is that the module location (`plugins/test_plugin.py`)  is _relative_; in this case, `_bootstrap_external.spec_from_file_location()` preprends `_os.getcwd()`, resulting in an absolute file path which is not the one you entered with `__BRYTHON__.add_file()`.

If you add a / before `plugins/test_plugin.py`, both in `add_files()` and in the Brython script, there is no error message.
