### ISSUE TITLE
AttributeError: 'browser' object has no attribute 'querySelector'

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2097]
Hello!

Below is the error message and an example that reproduces it.

## Error
```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_webcomponent_issue.html#__main__", line 16, in <module>
    webcomponent.define("ui-element", Element)
  File "file:///C:/Users/user1/issues/brython_webcomponent_issue.html#__main__", line 12, in connectedCallback
    span = div.querySelector("span")
           ^^^^^^^^^^^^^^^^^
AttributeError: 'browser' object has no attribute 'querySelector'
```

## Sample
```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - AttributeError: 'browser' object has no attribute 'querySelector'</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

        <script type="text/python">
from browser import console, window, html, document, webcomponent


class BaseComponent:
    _initialized: bool = False


class Element(BaseComponent):

    def connectedCallback(self):
        div = self.firstChild
        span = div.querySelector("span")
        console.debug(span.children)


webcomponent.define("ui-element", Element)
        </script>
    </head>
    <body onload="brython({debug: 1});">
        <ui-element>
            <div><span>test</span></div>
        </ui-element>
    </body>
</html>
```

Thank you for your time!

**Comment by PierreQuentel** [comment]
This is because `self.firstChild` is a Text element (for the linefeed after `<ui-element>`) , which doesn't have `.querySelector`.

It works if you replace `self.firstChild` by `self.firstElementChild`
