### ISSUE TITLE
NameError in list comprehension while unpacking and iterating over nested lists

### ISSUE THREAD

**Issue by tjnaughton** [brython-dev/brython#2112]
Hi,

Great work for so many years and especially synchronising with the CPython releases in recent years!

It seems this (below) is a regression, maybe introduced in Brython version 3.10.1 during the refactoring of comprehensions?

```
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list = [((1, 2),), ((3, 4),)]
>>> lc = [f'{a}{b}' for (a, b), in list]
>>> lc
['12', '34']
```

but with the latest version of Brython:
```
Brython 3.11.0 on Netscape 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
>>> list = [((1, 2),), ((3, 4),)]
>>> lc = [f'{a}{b}' for (a, b), in list]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <listcomp>
NameError: name 'a' is not defined
```

Thanks!

**Comment by PierreQuentel** [comment]
Thanks for the report and for the kind words :-)
