### ISSUE TITLE
from browser import timer -- no module named browser.timer

### ISSUE THREAD

**Issue by BobSquarePants** [brython-dev/brython#2116]
regarding my previous post : https://github.com/brython-dev/brython/issues/2115

I've tried to use the module browser.timer , but when I do a 

```python
from browser import document, confirm, prompt, window, alert, timer
```
I got
`ModuleNotFoundError: No module named 'browser.timer'`

Any ideas ?

**Comment by PierreQuentel** [comment]
Yes, you can create a script **`brython_modules.js`** with only the required modules for your application with `brython-cli make_modules`. It is explained in the [documentation](https://www.brython.info/static_doc/en/import.html).

**Comment by BobSquarePants** [comment]
Hi @PierreQuentel ,

I've tried `brython-cli modules` but I got -->

```shell
Traceback (most recent call last):
  File "/anonymized/bin/brython-cli", line 11, in <module>
    load_entry_point('brython==3.11.0', 'console_scripts', 'brython-cli')()
  File "/anonymized/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anonymized/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/anonymized/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/anonymized/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/anonymized/lib/python3.9/site-packages/brython/__main__.py", line 130
    match args.subcommand:
          ^
SyntaxError: invalid syntax

```

**Comment by PierreQuentel** [comment]
This is because the `match` keyword was introduced in Python 3.10 and you are using Python 3.9.

**Comment by BobSquarePants** [comment]
> This is because the `match` keyword was introduced in Python 3.10 and you are using Python 3.9.

:-1: on me :D

Thanks @PierreQuentel ! I'll try it in a couple of days
