### ISSUE TITLE
`.throw(...)` on generator in `yield from` causes `Exception: <Javascript TypeError>: $B.$is_exc is not a function`

### ISSUE THREAD

**Issue by mentalisttraceur** [brython-dev/brython#2126]
Using [the embedded console on the Brython webpage](https://brython.info/tests/console.html?lang=en):

```python
>>> def g():
...     yield 1
...     yield 2
... 
>>> def h(g):
...     yield from g()
... 
>>> i = h(g)
>>> next(i)
1
>>> i.throw(ValueError)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 2, in h
Exception: <Javascript TypeError>: $B.$is_exc is not a function
>>> 
```

Edit: this happens when the `yield from` is delegating to any iterator that has a `.throw` attribute, not just when delegating to other generators.

**Comment by mentalisttraceur** [comment]
Unclear from the outside if this is a separate issue or another symptom of the same issue:

```python
>>> i = h(g)
>>> 
>>> next(i)
1
>>> i.throw(ValueError(1), None)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'ValueError' object is not callable
```

**Comment by PierreQuentel** [comment]
Thanks for the report @mentalisttraceur !
