### ISSUE TITLE
[codecs] Can't decode or encode ROT13

### ISSUE THREAD

**Issue by tdmsilvino** [brython-dev/brython#2132]
I am trying to decode the "this" module but it's failing. This is the script:

```
<script type="text/python">
import codecs
import this
from browser import document, html

text = codecs.decode(this.s, "rot13")

document <= html.P(text)
</script>
```

When I run it in my browser I get this error message:
```
Error 404 means that Python module encodings.rot13 was not found at url https://cdn.jsdelivr.net/npm/brython@3.11.0/Lib/encodings/rot13.py
undefined 'rot13' 'error load_decoder' No module named 'encodings.rot13'
    at _b_.ModuleNotFoundError.$factory (eval at $B.$make_exc (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:346617), <anonymous>:3:15)
    at $download_module (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:438069)
    at StdlibStaticFinder.find_spec (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:448308)
    at f (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:222073)
    at import_engine (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:452525)
    at $B.$__import__ (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:455455)
    at Object.__import__ (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:296147)
    at load_decoder (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:398058)
    at $B.decode (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:402146)
    at res (https://cdn.jsdelivr.net/npm/brython@3.11.0/brython.min.js:1:429003)
......
brython.min.js:1 Traceback (most recent call last):
  File "http://localhost:8000/this.html#__main__", line 5, in <module>
    text = codecs.decode(this.s, "rot13")
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS._codecs.py", line 40, in decode
    return __BRYTHON__.decode(obj,encoding,errors)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: rot13
```

**Comment by tdmsilvino** [comment]
I just tested to encode a string to ROT13 and it's failing too.

Script:
```
<script type="text/python">
import codecs
from browser import document, html

text = codecs.encode("Beautiful is better than ugly.", "rot13")

document <= html.P(text)
</script>
```

Error:
```
Traceback (most recent call last):
  File "http://localhost:8000/this.html#__main__", line 5, in <module>
    text = codecs.encode("Beautiful is better than ugly.", "rot13")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS._codecs.py", line 50, in encode
    return bytes(__BRYTHON__.encode(obj,encoding,errors))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
LookupError: unknown encoding: rot13
```

**Comment by PierreQuentel** [comment]
Thanks for the report @tdmsilvino !

**Comment by tdmsilvino** [comment]
Now it works. Tks!
