### ISSUE TITLE
Module glob doesn't work

### ISSUE THREAD

**Issue by tdmsilvino** [brython-dev/brython#2133]
Hello! I am trying to use the module glob to list all the html files in the current directory but it doesn't work.

Script:
```
<script type="text/python">
from browser import document, html
#from browser.html import *
import glob

pages = glob.glob("*.html")
for page in pages:
    document <= html.A(page, href = page)
    document <= html.BR()
</script>
```

Error:
```
brython.js:14481 Traceback (most recent call last):
  File "http://localhost:8000/#__main__", line 5, in <module>
    pages = glob.glob("*.html")
                 ^^^^^^^^^^^^^^
  File "VFS.glob.py", line 28, in <module>
    return list(iglob(pathname,root_dir=root_dir,dir_fd=dir_fd,recursive=recursive,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.glob.py", line 78, in _iglob
    yield from _glob1(root_dir,basename,dir_fd,dironly,
               ^^^^^^^^^^^^^^^^^^^
  File "VFS.glob.py", line 106, in _glob1
    names=_listdir(dirname,dir_fd,dironly)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.glob.py", line 177, in _listdir
    return list(it)
           ^^^^^^^^
  File "VFS.glob.py", line 159, in _iterdir
    with os.scandir(arg)as it:
            ^^^^^^^^^^^^
  File "VFS.os.py", line 142, in scandir
    raise NotImplementedError
NotImplementedError
```

**Comment by PierreQuentel** [comment]
Hello,

This is not a bug, browsers cannot read the content of a folder on the local machine. All they can do is read the content of a file if its location is known.

**Comment by PierreQuentel** [comment]
In the commit referenced above I have added a message to the `NotImplementedError` raised by `os.scandir()`

**Comment by tdmsilvino** [comment]
Tks for the explanation
