### ISSUE TITLE
Python `compile()`, when called from JavaScript, crashes when processing a syntax error (rather than throwing a Python exception)

### ISSUE THREAD

**Issue by pmgl** [brython-dev/brython#2145]
So I am not sure we are supposed to do this, but it used to work for me with earlier versions of Brython. Here is how to reproduce on version 3.11.0 in the console (https://brython.info/tests/console.html?lang=en). I am first defining a python function which will compile and execute python code passed as a string ; then I am attaching it to the JavaScript context (`window.python = execute`) ; then I am calling `python(...)` from JavaScript:

```python
from browser import window
import traceback
import sys

def execute(str,filename):
  try:
    code = compile(str,filename,"exec")
    return exec(code,globals())
  except BaseException as err:
    exp = traceback.format_exception(err)
    sys.stderr.write(exp)
  except Error as err:
    exp = traceback.format_exception(err)
    sys.stderr.write(exp)

window.python = execute
```

Then from the JavaScript console:

```
python("-//- any incorrect syntax will do","myfile")
VM4107:86 Uncaught tb_frame
    at _b_.AttributeError.$factory (eval at $B.$make_exc (https://brython.info/src/py_exceptions.js:500:9), <anonymous>:3:15)
    at $B.attr_error (https://brython.info/src/py_exceptions.js:565:31)
    at attr_error (https://brython.info/src/py_builtin_functions.js:955:22)
    at $B.$getattr (https://brython.info/src/py_builtin_functions.js:1346:5)
    at $B.$getattr_pep657 (https://brython.info/src/py_utils.js:757:19)
    at eval (eval at VFSLoader.exec_module (https://brython.info/src/py_import.js:427:31), <anonymous>:1974:183)
    at Generator.next (<anonymous>)
    at $B.generator.send (https://brython.info/src/py_generator.js:110:23)
    at $B.generator.__next__ (https://brython.info/src/py_generator.js:57:25)
    at method (https://brython.info/src/py_object.js:290:40)
```

Whenever I pass a correct Python syntax it works correctly. Also if the Python script has a runtime error, it will be correctly caught and reported. Only syntax errors cause what is looking like a crash.

**Comment by PierreQuentel** [comment]
Merci Gilles :-)

The code should work now, with a slight modification : `sys.stdout.write()` doesn't write immediately to the console because there would be a line break each time, you have to call `sys.stdout.flush()` to actually print. Another solution would be to use `print()` instead.

**Comment by pmgl** [comment]
Thanks a lot for the quick fix Pierre!
I have tested the fix this morning and I confirm everything works perfectly for me now :-)
