### ISSUE TITLE
brython.info : symtable_visit_expr is not defined

### ISSUE THREAD

**Issue by yilmazdurmaz** [brython-dev/brython#2146]
I am trying to visit "brython.info" but this error happens. other links on this site also give lots of errors rendering the site unusable.

````
ReferenceError: symtable_visit_expr is not defined
    at eval (eval at window.eval (brython.info/:35:16), <anonymous>:1:1)
    at eval (<anonymous>)
    at window.eval (userscript.html?name=BlockAdblock%2520Blocker.user.js&id=eff429ff-bfe4-423d-8fc1-5720bf20ce20:35:16)
    at VISIT (brython.js:15912:33)
    at symtable_visit_stmt (brython.js:16065:1)
    at $B._PySymtable_Build (brython.js:15724:22)
    at $B.py2js (brython.js:4464:17)
    at $B.run_script (brython.js:4599:17)
    at $B.loop (brython.js:4757:10)
    at openCursor.onsuccess (brython.js:4698:1)
````

**Comment by PierreQuentel** [comment]
@yilmazdurmaz 
Thanks for reporting this, but I can't reproduce this bug, all the scripts on brython.info seem to work.
I see a reference to an adblocker in the error trace, could you try to disable it and see if it changes anything ?

**Comment by yilmazdurmaz** [comment]
Thanks @PierreQuentel , it is a small monkey script (mine is tampermonkey) that modifies `window.eval` function to prevent intrusive ads.

I guess this was expected as brython needs the eval function to interpret python sections. the site works when I disable the script for it.

Do you think it is possible without an eval? Or any work toward that? I guess I saw something like that for some other language but it is just a blurred memory.

**Comment by PierreQuentel** [comment]
In the commits referenced above I have removed most of the `eval()` in Brython, replacing them by calls to `Function()`. Does this fix the issue ?

**Comment by yilmazdurmaz** [comment]
I am now getting two errors, one is the below if I hard-refresh the page while dev-tools is open:
````
brython.js:483 
error ast.Add = function(){
}
brython.js:483 
        
       Uncaught ReferenceError: ast is not defined
    at eval (eval at window.eval (brython.info/:35:16), <anonymous>:1:1)
    at eval (<anonymous>)
    at window.eval (userscript.html?name=BlockAdblock%2520Blocker.user.js&id=eff429ff-bfe4-423d-8fc1-5720bf20ce20:35:16)
    at brython.js:482:5
    at brython.js:523:107
eval @ VM1521:1
window.eval @ userscript.html?name=BlockAdblock%2520Blocker.user.js&id=eff429ff-bfe4-423d-8fc1-5720bf20ce20:35
(anonymous) @ brython.js:482
(anonymous) @ brython.js:523

(index):143 
        
       Uncaught TypeError: brython is not a function
    at onload ((index):143:27)
onload @ (index):143
````

the second is exactly the same one in my first post.

That got me thinking because I was not expecting two results. This might be something after your changes or my first post also had the first error.

If you want to test your changes without me interfering, the script is at this address:
https://greasyfork.org/en/scripts/406036-blockadblock-blocker/code

**Comment by yilmazdurmaz** [comment]
above error corresponds to these following lines, but the current `brython.js` does not have "eval" in there.
````
try{eval(js)}catch(err){console.log('error',js)
throw err}
ast[kl].$name=kl
````
 I do hard-refresh meaning I should be getting the latest changes, but the page seems to get the older version. I guess there are places in html files not yet pointing to new code. can check and advice if it is on my side.

**Comment by yilmazdurmaz** [comment]
````
npx degit brython-dev/brython brython
python -m http.server
````
I have tried both the above commands and then saved/served the current "brython.info" page.

Your changes seem to be in effect in the repo but the currently served pages either are not pointing to the changes you made, or the server has cached the old content and continues serving it. please check what prevents updated content.

Thank you, by the way, for taking the time. when you think `eval`s are no more, then safely close this issue.

**Comment by PierreQuentel** [comment]
If you are running the scripts at brython.info, it is normal that you don't see the changes: the site is only updated at each new release.

To test the current development version with the latest commits, you can either clone the Github repository and use the scripts in it, or replace your version of **`brython.js`** and **`brython_stdlib.js`** by

```xml
<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
<script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>
```

**Comment by yilmazdurmaz** [comment]
I noticed you already have a `server.py` in the project root. I tested most parts of the cloned site. This was also an unexpected experience for me (I am a beginner to Brython) to see its capabilities.

These following ones in the gallery give "eval" errors you may want to check.
- Web Worker : Mandelbrot set
- custom HTML tag with Web Components
- Falling Blocks Game
- Interaction with Javascript libraries
  - Phaser (games engine)

I don't know about "Python tutorial slideshow (in French)" as it seems to be externally connected through the main site and thus still inherits the problem as it still uses unfixed library.
