### ISSUE TITLE
Exception: <Javascript TypeError>: cyclic object value

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2165]
Hello.

Something in the recent changes leads to the error mentioned.

But the performance is great! :)

```python
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

        <title>Brython -issue 202302124</title>

        <!-- Brython -->
        <!--
        <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/brython@3.11/brython.min.js">
        </script>
        <script type="text/javascript"
            src="https://cdn.jsdelivr.net/npm/brython@3.11/brython_stdlib.js">
        </script>
        -->
        <script 
            src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js">
        </script>
        <script 
            src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js">
        </script>
        <script>
function call(args, kwargs) {
  console.debug(args, kwargs)
  a = JSON.stringify(args)
  b = JSON.stringify(kwargs)
}

        </script>

        <script type="text/python">
from browser import window


def send(*args, **kwargs):
  # does not work on latest development snapshot, but works on 3.11.1
  window.call(args, kwargs)
  # does work/workaround
  #window.call(list(args), dict(kwargs))


send(1, 2, a="b", c="d")
        </script>
    </head>
    <body onload="brython({debug: 10});">
    </body>
</html>
```

```javascript
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_demo_20230224.html#__main__", line 11, in <module>
    send(1, 2, a="b", c="d")
  File "file:///C:/Users/user1/issues/brython_issue_demo_20230224.html#__main__", line 6, in send
    window.call(args, kwargs)
Exception: <Javascript TypeError>: cyclic object value
```

Thanks!

**Comment by PierreQuentel** [comment]
Hello,

Thanks for reporting this, with the latest changes it should work. 

When you do `window.call(args, kwargs)`, the Python arguments are translated to Javascript objects as described in [this page](https://www.brython.info/static_doc/en/jsobjects.html). Python dictionaries are translated to JS objects. The bug was caused by the fact that in one of the many versions I tried recently to improve the speed of arguments parsing, `kwargs` was not a Python dictionary.

In this case, if an argument passed to a JS function is not in the conversion table, it is passed "as is" to the function, and will probably cause the error you got when trying to stringify: such objects have an attribute `__class__`, which usually has itself its attribute `__class__` set to `type`, and `type.__class__` is `type`, hence the infinite loop.
