### ISSUE TITLE
print("") throws error instead of printing empty string

### ISSUE THREAD

**Issue by msbranicky** [brython-dev/brython#2175]
The following code does not work in Brython (PS - it worked 5 months ago, printing the empty string).  Google Colab and Python Shell both produce an empty string here.

>>> print("Hello"[:0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "https://brython.info/src/Lib/interpreter.py", line 109, in write
    self.interpreter.write(*args, **kw)
  File "https://brython.info/src/Lib/interpreter.py", line 502, in write
    self.cursor_to_end()
  File "https://brython.info/src/Lib/interpreter.py", line 307, in cursor_to_end
    pos = len(last_child.text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by msbranicky** [comment]
"Hello[:0]" works (returns "") but print("Hello"[:0]) throws the error

**Comment by msbranicky** [comment]
Simpler example, shows that it printing the empty string that throws the error.

>>> print("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "https://brython.info/src/Lib/interpreter.py", line 109, in write
    self.interpreter.write(*args, **kw)
  File "https://brython.info/src/Lib/interpreter.py", line 502, in write
    self.cursor_to_end()
  File "https://brython.info/src/Lib/interpreter.py", line 307, in cursor_to_end
    pos = len(last_child.text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by PierreQuentel** [comment]
Many thanks for the report of this embarrassing bug ! I have updated the console at brython.info.

**Comment by msbranicky** [comment]
Thank you!  It's a fantastic tool.  I use it for teaching a large intro programming class.  All the best!
