### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'open'

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2196]
Hello,

I'm still working on a simple issue demo to reproduce the error.

```python
Traceback (most recent call last):
  File "http://localhost:8082/#__main__", line 18, in onopen
    import elephas
  File "VFS.elephas/__init__.py", line 66, in <module>
    from . import ui
  File "[VFS.elephas.ui/__init__.py](chrome://devtools/content/webconsole/VFS.elephas.ui/__init__.py)", line 6, in <module>
    from . import splash
  File "VFS.elephas.ui.uiplugins.py", line 44, in <module>
    browser.aio.run(load_ui_plugins())
  File "VFS.elephas.ui.uiplugins.py", line 18, in load_ui_plugins
    module=UIPlugin.load_module(plugin_path)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.elephas.plugin_system.py", line 60, in load_module
    spec.loader.exec_module(module)
                ^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 936, in exec_module
    code=self.get_code(module.__name__)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 1073, in get_code
    source_bytes=self.get_data(source_path)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 1130, in get_data
    with _io.open_code(str(path))as file:
             ^^^^^^^^^^^^^^^^^^^^
  File "VFS._io.py", line 240, in open_code
    return __builtins__.open(file,encoding="utf-8")
           ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'open'
```

Thanks for your time!

**Comment by PierreQuentel** [comment]
Good catch, sorry for the regression !
