### ISSUE TITLE
Brython console crash

### ISSUE THREAD

**Issue by ed2050** [brython-dev/brython#2217]
Well I broke something  :).  Nothing important, simple to avoid... but could perhaps indicate other issues?

Enter this in [brython console](https://brython.info/tests/console.html?lang=en) and watch what happens.

`type (lambda)`

(yes it's not valid python.  still crashes though)
Not a hard crash.  Console doesn't eat cpu and stays responsive.
After that, anything you type produces this error:

```
UnboundLocalError: cannot access local variable 'filename' where it is not associated with a valuxTraceback (most recent call last):
  File "https://brython.info/src/Lib/interpreter.py", line 337, in keypress
    self.handle_line(event)
  File "https://brython.info/src/Lib/interpreter.py", line 405, in handle_line
    self.print_tb(exc)
  File "https://brython.info/src/Lib/interpreter.py", line 508, in print_tb
    traceback.print_exc(file=trace)
  File "https://brython.info/src/Lib/tb.py", line 87, in print_exc
    file.write(format_exc())
  File "https://brython.info/src/Lib/tb.py", line 76, in format_exc
    handle_repeats(filename, lineno, count_repeats)
```

Hope this helps.

**Comment by PierreQuentel** [comment]
Thanks for the report @ed2050 , and sorry for the late answer !
