### ISSUE TITLE
brython-cli make_package imports wrong module and breaks

### ISSUE THREAD

**Issue by cpressey** [brython-dev/brython#2221]
Hello and thank you for making and maintaining this open-source tool.

I'm trying out Brython on an existing project of mine, to see if I can get it to run on a web page.  My project is written in Python 3.9 so I'm using Brython 3.9.6.

In my project there is a package (called `vinegar`) which contains several modules (`parser.py`, `ast.py`, `interpreter.py`, etc.)  Following the Brython docs, I `cd` into the package directory and run `brython-cli --make_package vinegar`.  I get the following error:

```
Traceback (most recent call last):
  File "/home/cpressey/checkout/Vinegar/venv/bin/brython-cli", line 8, in <module>
    sys.exit(main())
  File "/home/cpressey/checkout/Vinegar/venv/lib/python3.9/site-packages/brython/__main__.py", line 165, in main
    from . import make_package
  File "/home/cpressey/checkout/Vinegar/venv/lib/python3.9/site-packages/brython/make_package.py", line 9, in <module>
    class Visitor(ast.NodeVisitor):
AttributeError: module 'ast' has no attribute 'NodeVisitor'
```

Near the top of `make_package.py` is the line `import ast`.  So, the problem is not very mysterious; since there is an `ast.py` in the current directory when `brython-cli` is run, it picks up that file instead of the expected one when importing `ast`.

I confirmed this is the problem, by adding the line `NodeVisitor = 123` to my `ast.py` file and observing that the error message changes:

```
TypeError: int() takes at most 2 arguments (3 given)
```

So, I guess there are three possible approaches to solving this problem.

One is to tell me that I need to rename my `ast` module to something else, something that doesn't conflict with any module that `brython-cli` imports.  This is clearly a workaround though.  I should be free to call my module `vinegar.ast` without much fear of conflict.

A second solution would be to prevent `brython-cli` from importing modules from the current directory.  I had understood that this can be accomplished in Python by `from __future__ import absolute_import`, but I guess my understanding is flawed, because if I try adding this line to the top of `make_package.py`, the behaviour doesn't change.

A third solution would be to question why the `brython-cli` command should require anything of the state of the _current directory_ in the first place.  I can't imagine it would be very difficult to make `make_package` be a subcommand that takes the package directory to operate on as a command-line argument.  And this would, in my opinion, be a much cleaner design -- although admittedly somewhat disruptive to change this after the fact, as it is a change to the user interface.

**Comment by PierreQuentel** [comment]
@cpressey 
I'm sorry for the very late answer. I could not reproduce the issue with the latest release (3.12.0).

- I put a script **`ast.py`** with this line: `x = 0` in a directory **`test_package`**
- in this directory I run `brython-cli make_package test_package`: no error message, a script **`test_package.brython.js`** is created (136 bytes)
- if I include this script in an HTML page with **`brython.js`** and a script
```xml
<script type="text/python">
import ast
print(ast.x)
</script>
```
the value "0" is printed in the browser console, meaning that it's the `ast` in the package that is imported, not the one in the standard library.

I didn't try with version 3.9.6. If there is a bug in this version I'm afraid the only advice I can give is to upgrade to a newer version.
