### ISSUE TITLE
browser.template.Template should NOT render the outer HTML

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2240]
Hi,

Currently, `browser.template.Template` is rendering the outer HTML.
However, this creates bugs and the need for dirty hacks :
```python
content = TEMPLATE.clone().content

# 1. Template can't work on documentFragment or on any element that hasn't a father (e.g. newly created element not yet inserted into the DOM/another element).
# "self.parentElement is not defined"
h4ck = html.DIV()
h4ck <= content
elem = html.DIV( h4ck )

parameters = {k[5:] : v for k, v in this.attrs.items() if k.startswith("data-")}
Template(h4ck).render(**parameters)

# 2. depending on whether the render had things to replace, the result may be either in elem.children[0].children or h4ck.children
children = elem.children[0].children
if (len(children) == 0):
    children = h4ck.children

# 3. can't use Template directly on a custom element, else we might have an infinite loop
# cf https://github.com/brython-dev/brython/issues/2236
this <= children
```

browser.template.Template should instead :
1. make a copy of the template element.
2. render the **inner** HTML of the current element, using the inner HTML of the copied template element.
3. (optionally?) render the attributes, one by one, of the current element using the attributes of the copied template element.

This would solve issue #2236 as well as preventing the little dirty h4ck 1 to 3.

Cordially,

**Comment by denis-migdal** [comment]
Okay, found another issue :

If no substitutions are done, the result is a text containing only line breaks.

```python
content = self._TEMPLATE.clone().content
			
			h4ck = html.DIV() if tagtype == DOMNode else tagtype()
			h4ck <= content
                        # ....
			elem = html.DIV( h4ck )
			
			parameters = {k[5:] : v for k, v in self.attrs.items() if k.startswith("data-")}
			Template(h4ck).render(**parameters)
			
			children = elem.children[0].childNodes
			if len(children) == 1 and children[0].text.count('\n') == len( children[0].text ):
				children = h4ck.childNodes

			self <= children
```

**Comment by denis-migdal** [comment]
Found a new bug :
If we pass a body to `Template` we get the following error message :
```
Traceback (most recent call last):
  File "http://localhost:3000/components/components.py", line 100, in <module>
    g.generate({"e": 44}) # remplace the element by a new one.
      ^^^^^^^^^^^^^^^^^^^
  File "http://localhost:3000/components/components.py", line 50, in generate
    Template(h4ck).render(**values)
                   ^^^^^^^^^^^^^^^^
  File "VFS.browser.template.py", line 306, in render
    for element in self.element.select("*[b-on]"):
                                ^^^^^^^^^^^^^^^^^
TypeError: DOMNode object doesn't support selection by selector brython.js:14610:56
```

**Comment by denis-migdal** [comment]
I also wrote a new class that should be safer than Template (?) :

Usage :
```html
<div id='test_a' data-test="{e}"><span>{e}</span></div>
<div id='test_b' data-test="{e}"><span>{e}</span></div>

<div>
	<div id='test_c' data-test="{e}"><span>{e}</span></div>
</div>
```
```python
t = document.querySelector('#test_a');
g = Generator(target=t)
g.generate({"e": 42}) # change the children

t = document.querySelector('#test_b');
g = Generator(content=[t])
print( g.generate({"e": 43}) ) # create new elements

t = document.querySelector('#test_c');
g = Generator(target=t.parentElement, content=[t])
g.generate({"e": 44}) # remplace the element by a new one.
```

Code :
```python
class Generator:

	def __init__(self, target=None, content=None):
		if content == None:
			content = target.childNodes

		content = [c.clone() for c in content]
		self.target = target

		self.template = target.clone() if target != None else html.DIV()
		self.template.replaceChildren(*content)

	def generate(self, values):

		h4ck = self.template.clone()

		tagtype = h4ck.tagName
			
		elem = None
		if tagtype in [html.TD, html.TR, html.TBODY, html.TFOOT, html.THEAD]:

			cur_elem = h4ck
			tag = tagtype
			if tag == html.TD:
				tag = html.TR
				cur_elem = tag( cur_elem )
				if elem == None:
					elem = cur_elem
			if tag == html.TR:
				tag = html.TBODY
				cur_elem = tag( cur_elem )
				if elem == None:
					elem = cur_elem

			cur_elem = html.TABLE( cur_elem )
			if elem == None:
				elem = cur_elem
		else:
			elem = html.DIV( h4ck )
			
			Template(h4ck).render(**values)

			
			children = elem.children[0].childNodes
			if len(children) == 1 and children[0].text.count('\n') == len( children[0].text ):
				children = h4ck.childNodes

		if self.target == None:
			return children

		#for attrname in h4ck.attrs:
		#	self.target.attrs[attrname] = h4ck.attrs[attrname]

		self.target.replaceChildren( *children )

		return self.target
```

**Comment by CookiePLMonster** [comment]
Are you having any luck rendering the arguments from a cloned template, even using this hack? I tried my best to replicate it, but variables defined like
```html
<template id="footnote-template">
<li id="#fn:{id}" role="doc-endnote"><p>{note}&nbsp;<a href="#fnref:{id}" class="reversefootnote" role="doc-backlink">&larrhk;</a></p></li>
</template>
```

are just not being substituted with a `Template(hack).render(id='x', note='y'` call.

**Comment by denis-migdal** [comment]
> Are you having any luck rendering the arguments from a cloned template, even using this hack? I tried my best to replicate it, but variables defined like

I worked for me. Maybe a bug has been introduced in the new Brython version ?

TBF, now I use my own implementation of WebComponent : BLISS.

**Comment by CookiePLMonster** [comment]
> I worked for me. Maybe a bug has been introduced in the new Brython version ?

The following outputs un-rendered HTML for me, which means I get a footnote saying `{note}`.

Brython:
```python
newFootnote = document['footnote-template'].clone().content
h4ck = html.DIV()
h4ck <= newFootnote
elem = html.DIV(h4ck)

Template(h4ck).render(id='test', note='Testing')
document['output-footnotes'] <= h4ck.childNodes
```

HTML:
```html
<template id="footnote-template">
<li id="#fn:{id}" role="doc-endnote"><p>{note}&nbsp;<a href="#fnref:{id}" class="reversefootnote" role="doc-backlink">&larrhk;</a></p></li>
</template>
```

Not sure if what I am doing is supported at all - ideally, I'd like to define templates of my elements in HTML and have Brython output them however I see fit, on demand.

**Comment by denis-migdal** [comment]
You missed 2 lines :

```python
newFootnote = document['footnote-template'].clone().content

# h4ck
h4ck = html.DIV()
h4ck <= newFootnote

elem = html.DIV(h4ck)
Template(h4ck).render(id='test', note='Testing')

# get result :
children = elem.children[0].childNodes
if len(children) == 1 and children[0].text.count('\n') == len( children[0].text ):
	children = h4ck.childNodes

document['output-footnotes'] <= children
```

Indeed, sometimes the result is in elem, other times it is in h4ck.
You can try to print them both to see which one contains your result.

**Comment by CookiePLMonster** [comment]
> You missed 2 lines :

Awesome, this works, thank you! I also found out that just specifying `document['output-footnotes'] <= elem.childNodes` also works.

This is much cleaner than manually building HTML from Brython, like I did before:
```python
        note = html.P('No effect.' + chr(160) + html.A(chr(0x21A9), href='#fnref:no-effect', Class='reversefootnote', role='doc-backlink')
                                + chr(160) + html.A(chr(0x21A9) + html.SUP('2'), href='#fnref:no-effect:1', Class='reversefootnote', role='doc-backlink'))
        document['output-footnotes'] <= html.LI(note, id='#fn:no-effect', role='doc-endnote')
```
