### ISSUE TITLE
TypeError: obj is null when importing windows to globals()

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2248]
Hi,

I'm currently writing code to import all windows elements to the brython globals().
(also could be nice to have an attribute in script tags to enable it auto-magically).

However, it doesn't seem to work for some elements resulting in the following error :
```TypeError: obj is null brython.js:14612:56
    flush https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:14612
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5522
    show_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:8074
    (Asynchrone : promise callback)
    run https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9260 > Function:244
    call1 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5211
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5205
    defineCustomElements66 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:503
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5205
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:22
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4800
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4813
    run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    onreadystatechange https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4769
    (Asynchrone : EventHandlerNonNull)
    ajax_load_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4765
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    run_scripts https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4592
    brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4540
    onload https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490
    (Asynchrone : EventHandlerNonNull)
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490
    (Asynchrone : EventListener.handleEvent)
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4488
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4636
```

``` the code :
from browser import window

g = globals()
for x in window.Object.getOwnPropertyNames(window):

	if x in g:
		continue

        if x == "print": # don't want to print the webpage when trying to use python print() function xDD
                 continue

	if x.startswith("on"): # else bug
		continue

	if x in ["opener", "frameElement", "InstallTrigger", "def_value"]: # else bug
		continue

	g[x] = getattr(window, x, None)
```

Cordially,

**Comment by denis-migdal** [comment]
I also tried to test if the value was null, I must doing it wrong as I have the following errors :
```python
value = getattr(window, 'opener', None)
print(value, NULL)
```

```
TypeError: obj is null brython.js:14612:56
    flush https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:14612
    method https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5522
    show_error https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:8074
    (Asynchrone : promise callback)
    run https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 9260 > Function:244
    call1 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5211
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5205
    defineCustomElements68 https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:513
    call https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5205
    anonymous https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:22
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4800
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4813
    run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    run_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    onreadystatechange https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4769
    (Asynchrone : EventHandlerNonNull)
    ajax_load_script https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4765
    loop https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814
    run_scripts https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4592
    brython https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4540
    onload https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490
    (Asynchrone : EventHandlerNonNull)
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490
    (Asynchrone : EventListener.handleEvent)
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4488
    <anonyme> https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4636
```


```python
value = getattr(window, 'opener', None)
print( type(value) )
```
```
Traceback (most recent call last):
  File "http://localhost:3000/components/components.py", line 23, in <module>
    print( type(value) )
JavascriptError: kls is null

Javascript error
TypeError: kls is null
type<@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5722:1
$B.$call/<@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5205:52
anonymous@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:48:63
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4800:53
$B.run_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632:17
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
$B.run_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632:17
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
$B.ajax_load_script/req.onreadystatechange@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4769:1
EventHandlerNonNull*$B.ajax_load_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4765:1
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
run_scripts@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4592:4
$B.parser.brython@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4540:89
ev.target.body.onload@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490:43
EventHandlerNonNull*@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490:1
EventListener.handleEvent*@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4488:17
@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4636:21
brython.js:14612:56
```

```python
value = getattr(window, 'opener', None)
print( value == NULL)
```
```
Traceback (most recent call last):
  File "http://localhost:3000/components/components.py", line 24, in <module>
    print( value == NULL)
JavascriptError: x is null

Javascript error
TypeError: x is null
$B.rich_comp@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:5320:8
anonymous@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js line 4800 > Function:48:36
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4800:53
$B.run_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632:17
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
$B.run_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4632:17
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
$B.ajax_load_script/req.onreadystatechange@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4769:1
EventHandlerNonNull*$B.ajax_load_script@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4765:1
$B.loop@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4814:10
run_scripts@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4592:4
$B.parser.brython@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4540:89
ev.target.body.onload@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490:43
EventHandlerNonNull*@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4490:1
EventListener.handleEvent*@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4488:17
@https://raw.githack.com/brython-dev/brython/master/www/src/brython.js:4636:21
brython.js:14612:56
```

**Comment by denis-migdal** [comment]
Funny enough :
```javascript
window.foo = function() { return null }
window.faa = function() { return undefined }
```
```python
print(foo())
print(faa())
```
gives
```
None
<Javascript undefined>
```

I'm investigating it. I guess this is due to getter/setter ?

**Comment by denis-migdal** [comment]
Also :
```python
def foo():
	return None
def faa():
	return NULL

window.foo = foo
window.faa = faa


eval("console.log(foo());")
eval("console.log(faa())")
```
Gives :
```
Object { __class__: {…}, __doc__: "" }
null
```

I think such asymmetry is dangerous.
Either None and null should be considered as different values, or all JS null should be converted to None in Python, and all None in Python should be converted to null in DOM/JS.

**Comment by denis-migdal** [comment]
Thanks. I didn't fully tested it yet.

However I noticed something : in Python non-returning functions return `None`, that is currently converted to `null` by Brython. However, in JS, non-returning functions return `undefined`.

Therefore should `None` be converted to `undefined` instead (and `undefined` converted to `None`) ? or will it break something else ?.

Or should Brython internally have 2 `None` that'd be converted either to `undefined` if coming from a non-returning function (or using `return`), and `null` otherwise ?

**Comment by denis-migdal** [comment]
> Or should Brython internally have 2 None that'd be converted either to undefined if coming from a non-returning function (or using return), and null otherwise ? But that'd cause other issues...

Maybe this could be a solution... `<None-undefined>` and `<None-null>` could be equal (in JS `null == undefined`) but :
- `<None-undefined> != null` (in JS `null !== undefined`)
- `<None-null> != undefined` (in JS `null !== undefined`)

It'd be a little strange... but there are strange things in JS anyways xD.

**Comment by denis-migdal** [comment]
After a good night of sleep, an alternative :

- JS to Brython
    - `undefined` converted to `<None origin=undefined>`
    - `null` converted to `<None origin=null>`
- Brython to JS
   - `<None origin=undefined>` converted to `undefined`.
   - `<None origin=null>` converted to `null`.
- Brython
   - `None` keyword is `<None origin=null>`
   - implicit `None` in function return value is `<None origin=undefined>`
   - `<None origin=undefined> == <None origin=null>` and `<None origin=undefined> is <None origin=null>` are both `True` to not change Python behavior.
   - `<None origin=null> == javascript.NULL` is `True` but `<None origin=null> == javascript.UNDEFINED` and `<None origin=null> is javascript.NULL` are `False` ?
   - `<None origin=undefined> == javascript.UNDEFINED` is `True` but `<None origin=UNDEFINED> == javascript.NULL` and `<None origin=UNDEFINED> is javascript.UNDEFINED` are `False` ?

**Comment by PierreQuentel** [comment]
Thanks for all the comments, it helps clarify things that were confusing in interactions between JS and Brython.

After a series of commits yesterday and today, things should be more clear:
- if a Javascript object `js_obj` is `undefined`, then in Brython, `window.js_obj` is `javascript.UNDEFINED`. Consequently, if a JS function `js_func()` doesn't return anything, `window.js_func()` is `javascript.UNDEFINED`
- if a Javascript object `js_obj` is `null`, then in Brython, `window.js_obj` is `javascript.NULL`
- `None` is not converted when used in Javascript code

**Comment by denis-migdal** [comment]
Thanks :)

> None is not converted when used in Javascript code

Only issue I see is that if ones creates a Brython callback that doesn't return anything, he'll have to explicitly return `javascript.UNDEFINED`, in order to prevent strange interactions with JS (which can be sources of errors).

It'd also prevent him from directly using a Python function defined by somebody else, or used somewhere. Indeed Python would expect such functions to return `None`, not `javascript.UNDEFINED`.


Hence using 2 `None` that would be the "same" in Brython, but different in JS might solve it ?
As well as helping Brython devs to not having to handle strange JS values (null and undefined) themselves as they'd be converted to `None` ?

**OR**

When giving `None` to JS, throwing an exception "You can't use None in JS, please convert it to 'undefined' or 'null' before hands" ? That could help preventing issues ?

Also making `undefined == None` and `null == None` ? So that Python devs would see `null` and `undefined` as if it was `None` ?

**Comment by denis-migdal** [comment]
> When giving None to JS, throwing an exception "You can't use None in JS, please convert it to 'undefined' or 'null' before hands" ? That could help preventing issues ?

Alternatively :
- having a `console.warn()` with a trace instead of raising an exception ? which could be deactivated depending on log level ?

**Comment by denis-migdal** [comment]
I'm closing this issue as it is now fixed.
I'll be opening a new issue on a related topic
