### ISSUE TITLE
AttributeError: 'SimpleNamespace' object has no attribute 'cache_tag'

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2286]
Hello Pierre,

one of your recent commits is causing my plugin system to stop working. You can find the error message and an example below.

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_demo_20231024.html#__main__", line 34, in <module>
    load_plugin("plugins/test_plugin.py")
  File "file:///C:/Users/user1/issues/brython_issue_demo_20231024.html#__main__", line 26, in load_plugin
    module = importlib.util.module_from_spec(spec)
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "VFS._frozen_importlib.py", line 594, in module_from_spec
    _init_module_attrs(spec,module)
  File "VFS._frozen_importlib.py", line 573, in _init_module_attrs
    if spec.cached is not None :
       ^^^^^^^^^^^
  File "VFS._frozen_importlib.py", line 414, in cached
    self._cached=_bootstrap_external._get_cached(self.origin)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 613, in _get_cached
    return cache_from_source(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 509, in cache_from_source
    tag=sys.implementation.cache_tag
            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SimpleNamespace' object has no attribute 'cache_tag'
```

```python
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags-->
        <meta charset="utf-8">

        <title>Brython - AttributeError: 'SimpleNamespace' object has no attribute 'cache_tag'</title>

        <!-- Brython -->
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"></script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"></script>

<script type="text/javascript">
__BRYTHON__.add_files({
    "data/test.txt": {
        "content": "dGVzdA==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    },
    "plugins/test_plugin.py": {
        "content": "aXNfY2xpZW50ID0gVHJ1ZQoKaW1wb3J0IG9zCmltcG9ydCB0cmFjZWJhY2sKZnJvbSBicm93c2VyIGltcG9ydCBkb2N1bWVudCx3aW5kb3csY29uc29sZSxhaW8KaW1wb3J0IGpzb24KCnByaW50KCJIZWxsbyBXb3JsZCEiKQ==\n",
        "ctime": 1665590786.2691407,
        "mtime": 1665590786.2700846
    }})
    </script>

    <script type="text/python">
# Standard library imports.
import sys
from browser import console
import browser.aio
import pathlib
import importlib.util

# Related third party imports.

# Local application/library specific imports.


def load_plugin(module_path, add_to_sys_modules=True):
    stem = pathlib.Path(module_path).stem
    if stem[0].isdigit():
        tmp = stem.split("_", 1)
        if len(tmp) == 2:
            stem = tmp[1]
    module_name =  "ui_plugin_" + stem
    if module_name in sys.modules:
        print("{} already loaded".format(module_name))
        return sys.modules[module_name]
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    if spec is None:
        raise FileNotFoundError(module_path)
    module = importlib.util.module_from_spec(spec)
    module.is_plugin = True
    if add_to_sys_modules:
        sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


load_plugin("plugins/test_plugin.py")
 

        </script>
    </head>
    <body>
    </body>
</html>
```

Thanks in advance!

**Comment by PierreQuentel** [comment]
Sorry about that @moepnse !

**Comment by moepnse** [comment]
No problem. Unfortunately, it still does not work.
A new error occurs.

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_demo_20231024.html#__main__", line 34, in <module>
    load_plugin("plugins/test_plugin.py")
  File "file:///C:/Users/user1/issues/brython_issue_demo_20231024.html#__main__", line 26, in load_plugin
    module = importlib.util.module_from_spec(spec)
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "VFS._frozen_importlib.py", line 594, in module_from_spec
    _init_module_attrs(spec,module)
  File "VFS._frozen_importlib.py", line 573, in _init_module_attrs
    if spec.cached is not None :
       ^^^^^^^^^^^
  File "VFS._frozen_importlib.py", line 414, in cached
    self._cached=_bootstrap_external._get_cached(self.origin)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 613, in _get_cached
    return cache_from_source(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.importlib._bootstrap_external.py", line 524, in cache_from_source
    if sys.pycache_prefix is not None:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'pycache_prefix' [brython.js:15016:56](https://raw.githack.com/brython-dev/brython/master/www/src/brython.js)
```

**Comment by moepnse** [comment]
Unfortunately, it still does not behave as before. I have not yet been able to write a simple demo that reproduces the error.

```python
Traceback (most recent call last):
  File "http://localhost:8082/#__main__", line 18, in onopen
    import elephas
  File "VFS.elephas/__init__.py", line 68, in <module>
    from . import ui
  File "[VFS.elephas.ui/__init__.py](chrome://devtools/content/webconsole/VFS.elephas.ui/__init__.py)", line 6, in <module>
    from . import splash
  File "VFS.elephas.ui.uiplugins.py", line 44, in <module>
    browser.aio.run(load_ui_plugins())
  File "VFS.elephas.ui.uiplugins.py", line 41, in load_ui_plugins
    ui_plugin_base_component.register()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'register'
```
