### ISSUE TITLE
error in the implementation of hmac

### ISSUE THREAD

**Issue by longnetwork** [brython-dev/brython#2458]
```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <script src="brython.min.js"></script>
        <script src="brython_stdlib.min.js"></script>

    </head>

    <body onload="brython({debug: 0, cache: true})">
    <script type="text/python">

        import hmac

        hmac_hash = hmac.new("secret_keys_string".encode(), "message".encode(), 'sha256')

        print(hmac_hash)

    </script>
    </body>
</html>
```
Produces an error:
```
Traceback (most recent call last):
  File "home/mint/Work/codeTests/python/python_in_browser/brython/test.html", line 4, in <module>
    hmac_hash = hmac.new("secret_keys_string".encode(), "message".encode(), 'sha256')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.hmac.py", line 184, in new
    return HMAC(key,msg,digestmod)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.hmac.py", line 64, in __init__
    self._init_old(key,msg,digestmod)
  File "VFS.hmac.py", line 82, in _init_old
    self.digest_size=self._inner.digest_size
                     ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'hash' object has no attribute 'digest_size'
```

**Comment by PierreQuentel** [comment]
Thanks for the report @longnetwork !
