### ISSUE TITLE
Setting an observed attribute results in an unexpected exception

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2459]
Hello!

Setting an observed attribute results in an unexpected exception.

An example and the exception can be found below this text.

Thanks in advance!

```python
<html>

    <head>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"
            crossorigin="anonymous">
        </script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"
            crossorigin="anonymous">
        </script>
    </head>

    <body>
        <script type="text/python">
from browser import webcomponent, html, console


class Container:

    observedAttributes = ["test"]

    def __init__(self):
        # Create a shadow root
        shadow = self.attachShadow({'mode': 'open'})

        # Create a new <link> and let it point to container.css
        link = html.LINK(rel="stylesheet", href="container.css")
        shadow <= link

        # vvvv - Move current webcomponent's children to the Shadow DOM
        # Create a new <div>
        div = html.DIV()
        # Move each child element into the <div>
        for element in self.children:
            div.appendChild(element)
        # Add the newly created <div> to the Shadow Dom
        shadow <= div
        # ^^^^

    def connectedCallback(self):
        print("connected callback", self)
        self.attrs["test"] = "test1"
        self.attrs["test"] = "test2"

    def attributeChangedCallback(self, name, old_value, new_value):
        console.debug("attributeChangeCallback", self, name, old_value, new_value)
        setattr(self, name, new_value)

webcomponent.define("ui-container", Container)

        </script>
        <h1>New UI-Container</h1>
        <ui-container>
            <div>Test</div>
        </ui-container>
    </body>

</html>
```

```python
Traceback (most recent call last):
  File "C:/Users/moepnse/Downloads/brython_shadow_dom_sample.html", line 35, in <module>
    webcomponent.define("ui-container", Container)
  File "C:/Users/moepnse/Downloads/brython_shadow_dom_sample.html", line 28, in connectedCallback
    self.attrs["test"] = "test1"
JavascriptError: TypeError: last is null
[brython.js:11019:18](https://raw.githack.com/brython-dev/brython/master/www/src/brython.js)
Traceback (most recent call last):
  File "C:/Users/moepnse/Downloads/brython_shadow_dom_sample.html", line 35, in <module>
    webcomponent.define("ui-container", Container)
  File "C:/Users/moepnse/Downloads/brython_shadow_dom_sample.html", line 29, in connectedCallback
    self.attrs["test"] = "test2"
JavascriptError: TypeError: last is null
```

**Comment by PierreQuentel** [comment]
Thanks @moepnse !

With the commit above you get this more helpful error message
```
Traceback (most recent call last):
  File "tests/issue_2459.html", line 35, in <module>
    webcomponent.define("ui-container", Container)
  File "tests/issue_2459.html", line 29, in connectedCallback
    self.attrs["test"] = "test2"
TypeError: attributeChangedCallback() takes 4 positional arguments but 5 were given
```

This is because `attributeChangedCallback` is called with an additional attribute (not sure what its value is), as you can see in this Javascript-only example
```xml
<script>
class MyCustomElement extends HTMLElement {
  static observedAttributes = ["size"];

  constructor() {
    super();
  }

  connectedCallback(){
    console.log('connected callback', this)
    this.setAttribute('size', 'test1')
  }

  attributeChangedCallback(name, oldValue, newValue) {
    console.log('arguments of attributeChangedCallback', arguments) // there are 4 arguments !
    console.log(
      `Attribute ${name} has changed from ${oldValue} to ${newValue}.`,
    );
  }
}

customElements.define("my-custom-element", MyCustomElement);
</script>

<my-custom-element></my-custom-element>
```

The solution in your Brython code is just to add an additional argument `*args` at the end of the definition of `attributeChangedCallback()`
