### ISSUE TITLE
cannot slice sys.version_info ?

### ISSUE THREAD

**Issue by fwyzard** [brython-dev/brython#2466]
Using
```python
import sys
print(sys.version_info[0:2])
```
with Brython 3.12.0 fails with
```
Traceback (most recent call last):
  File "home/fwyzard/test/brython/process.html", line 6, in <module>
    print(f'python version: {sys.version_info[0:2]}')
  File "VFS.sys.py", line 16, in __getitem__
    raise KeyError(key)
KeyError: slice(0, 2, None)
```

while it works fine with regular python:
```
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version_info[0:2])
(3, 10)
```

**Comment by PierreQuentel** [comment]
Thanks for the report @fwyzard !

I could reproduce the bug in release 3.12.3 but it is fixed in the current development version. I will publish a new release shortly.
