### ISSUE TITLE
Problem with `inspect.getframeinfo`

### ISSUE THREAD

**Issue by fwyzard** [brython-dev/brython#2468]
With Brython, this use of `inspect.getframeinfo`
```python
def test():
    print(inspect.getframeinfo(sys._getframe(1)))

test()
```

fails with
```
Traceback (most recent call last):
  File "home/fwyzard/test/brython/process.html", line 8, in <module>
    test()
  File "home/fwyzard/test/brython/process.html", line 6, in test
    print(inspect.getframeinfo(sys._getframe(1)))
          ^
  File "VFS.inspect.py", line 1695, in getframeinfo
    positions=_get_code_position(frame.f_code,frame.f_lasti)
                                              ^
AttributeError: 'frame' object has no attribute 'f_lasti'. Did you mean: 'f_lasti'? brython.js:10974:56
```

It works with regular python:
```
>>> def test():
...     print(inspect.getframeinfo(sys._getframe(1)))
... 
>>> test()
Traceback(filename='<stdin>', lineno=1, function='<module>', code_context=None, index=None)
```

**Comment by fwyzard** [comment]
More simply, running in Brython
```python
import sys
print(sys._getframe().f_lasti)
```
results in
```
Traceback (most recent call last):
  File "home/fwyzard/test/brython/process.html#__main__", line 5, in <module>
    print(sys._getframe().f_lasti)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'frame' object has no attribute 'f_lasti'. Did you mean: 'f_lasti'? brython.js:11020:18
```

**Comment by PierreQuentel** [comment]
Thanks for the report Andrea. The attribute is not relevant in Brython (it doesn't generate bytecode) but must be set to something to avoid breaking other code. In this commit it is always set to 0.

**Comment by fwyzard** [comment]
Thanks for the fix, I'll try to run the full application with the latest version of Brython!
