### ISSUE TITLE
Error in ZLib compression with some data

### ISSUE THREAD

**Issue by jibalamy** [brython-dev/brython#2516]
Hello,

I encounter problems with Zlib compression using specific data. 

Here is a simple example:

```
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<script type="text/javascript" src="brython.js"></script>
<script type="text/javascript" src="brython_stdlib.js"></script>
</head>
<body>
<script type="text/python">

import zlib

s = """(["Clinician","",69,[{"name":"drugera1","code":"B05BA03","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":10269,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera1')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"},{"name":"drugera2","code":"N05AG02","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":6998,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera2')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"},{"name":"drugera3","code":"C01DA02","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":29808,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera3')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"},{"name":"drugera4","code":"C01AA05","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":4253,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera4')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"},{"name":"drugera5","code":"C03XA01","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":32737,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera5')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"},{"name":"drugera6","code":"L04AB01","source":"Saisie manuelle","poso":"À l'occasion","theriaque_code":21444,"automedication":false,"has_for_indication_label":"Indication ? <span onclick=\"add_indic_problem('drugera6')\" class=\"button2 minibutton\" title=\"Ajouter le problème\">Aj. problème</span>"}],[{"name":"conditionera1","code":"I64","source":"Saisie manuelle"},{"name":"conditionera2","code":"C71.2","source":"Saisie manuelle"},{"name":"conditionera3","code":"W92","source":"Saisie manuelle"},{"name":"conditionera4","code":"Z32.1","source":"Saisie manuelle"},{"name":"conditionera5","code":"E73.1","source":"Saisie manuelle"},{"name":"conditionera6","code":"R63.4","source":"Saisie manuelle"}],[],[],[],[],"","","","","","","",[],[]],["","","","","","",""])"""

print(zlib.compress(s.encode("utf8")))
  
</script>    
</body>
</html>
```

Which produces :

```
Traceback (most recent call last):
  File "tmp/t.html#__main__", line 7, in <module>
    print(zlib.compress(s.encode("utf8")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.zlib.py", line 703, in compress
    payload=compressor.compress(data)+compressor.flush()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.zlib.py", line 782, in compress
    compress_dynamic(out,source,store,lit_len_count,distance_count)
  File "VFS.zlib.py", line 610, in compress_dynamic
    write_int(length,3)
  File "VFS.zlib.py", line 101, in write_int
    raise ValueError("can't write value on {} bits".format(nb))
ValueError: can't write value on 3 bits
```

Additionally, using the following value for s :

`s = "x" * 1000`

I obtain a different error:

```
Traceback (most recent call last):
  File "tmp/t.html#__main__", line 7, in <module>
    print(zlib.compress(s.encode("utf8")))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.zlib.py", line 703, in compress
    payload=compressor.compress(data)+compressor.flush()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.zlib.py", line 782, in compress
    compress_dynamic(out,source,store,lit_len_count,distance_count)
  File "VFS.zlib.py", line 575, in compress_dynamic
    distance_codes=normalized(codelengths_from_frequencies(distance_count))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "VFS.zlib.py", line 267, in codelengths_from_frequencies
    tree.reduce(15)
  File "VFS.zlib.py", line 227, in reduce
    while self.length()>maxlevels:
          ^^^^^^^^^^^^^
  File "VFS.zlib.py", line 169, in length
    set_level(self.root)
  File "VFS.zlib.py", line 164, in set_level
    for child in node.children:
                 ^^^^^^^^^^^^^
AttributeError: 'Node' object has no attribute 'children'
```

(this might be a distinct bug).

Thank you for support,
Jiba

**Comment by PierreQuentel** [comment]
Thank you Jiba !
