### ISSUE TITLE
Not an URL when calling `runPythonSource()` in Deno

### ISSUE THREAD

**Issue by denis-migdal** [brython-dev/brython#2521]
A little bug I encountered when trying to execute Brython inside Deno :

```
Error: not a url: #python_script_666512880644291
    at Object.$B.strip_host (eval at load_brython (file:///home/demigda/Data/Recherche/Git/VSHS-TS-/index.ts:61:3), <anonymous>:1:2062)
    at Object.$B.run_script (eval at load_brython (file:///home/demigda/Data/Recherche/Git/VSHS-TS-/index.ts:61:3), <anonymous>:1:58356)
    at Object.$B.runPythonSource (eval at load_brython (file:///home/demigda/Data/Recherche/Git/VSHS-TS-/index.ts:61:3), <anonymous>:1:8984
```

**Comment by denis-migdal** [comment]
The code below work (use the previous version), BUT if we use the 3.13.0 version from the CDN :

1. It generates the `Error: not a url: #_` error (with the provided module name is `_`).
2. Sometimes I also got the following error (but can't reproduce it consistantly) :
```
TypeError: Cannot set properties of undefined (setting '__name__')
    at eval (eval at <anonymous> (blob:null/3570ed38-14e7-4ef2-9ae8-9a6c6e878d1d:13:5), <anonymous>:8:17)
```

```ts
let brython: any = null;

async function load_brython() {
	if( brython !== null)
		return;

	//brython = await (await fetch( "https://cdnjs.cloudflare.com/ajax/libs/brython/3.13.0/brython.min.js" )).text();
	const dir = import.meta.url.slice(6, import.meta.url.lastIndexOf('/') );
	brython = await Deno.readTextFile(dir + '/brython.js');

	// @ts-ignore
	window.$B = window.__BRYTHON__ = {}; // why is it required ???
	eval(brython);
}

if( is_brython ) {

		await load_brython();

		//TODO: duplicated code with playground... (! \` vs \\\`).
		code = `const $B = globalThis.__BRYTHON__;

		$B.imported["exec"] = {};
		$B.frames_stack = [];

		const js = $B.py2js(\`${code}\`, "exec").to_js();

		eval(js)
		//const f = new Function(js)();

		const module = __BRYTHON__.imported["exec"];

		const fct = __BRYTHON__.pyobj2jsobj(module.RequestHandler);

		export default fct;
		`;
		//TODO load __BRYTHON__...

	}

	const url = URL.createObjectURL( new Blob([code], {type: "text/javascript"}));

	//TODO Brython switch...
	module = await import( url );
```

**Comment by denis-migdal** [comment]
On the last Brython version:

Setting `$B.isNode=true;` create new errors :
```
Cannot set properties of undefined (setting '__BRYTHON__')
```

Setting `$B.isWebWorker=true` create new erros :
```
ImportError: cannot import name 'window'. Did you mean: 'undefined'?
JavascriptError: ReferenceError: inner is not defined
```
If `from browser import window` supported in WebWorker ?
It seems it isn't :
```js
browser.__path__=browser.__file__
if($B.isNode){delete browser.window
delete browser.win}else if($B.isWebWorker){browser.is_webworker=true
delete browser.window
delete browser.win
}
```

I'll open a new issue, and I'll continue my investigations.

Dirty fixing the issue in `strip_host` due to:
```js
var parsed_url=new URL(url)
```
create new errors:
```
ReferenceError: inner is not defined
document.dispatchEvent is not a function
```

Creating a fake  `document.dispatchEvent()` generate an error :
```
Cannot read properties of undefined (reading 'src')
```

**Comment by denis-migdal** [comment]
```
ReferenceError: inner is not defined
```

Seems to occur when I do : 
```python
self.Response.new("Hello World ;)").
```
Although  the same code works in the browser.
And the following code works too in Deno :
```python
self.Response.new( await request.text() ).
```

**Comment by denis-migdal** [comment]
It seems the `inner is not defined` error is generated in the `py2js` step, when converting the Python code to the AST.

**Comment by denis-migdal** [comment]
Okay, now it works by adding :
```js
globalThis.$B  = globalThis.__BRYTHON__ = {};
globalThis.inner = null;
```

To make Brython work on Deno, I had to :
1. define the previous symbols globally ;
2. make `$B.isWebBrowser=true` ;
3. make `strip_host(url)` returning `url`.

**Comment by denis-migdal** [comment]
Upgraded my version of Deno.

Had to add :
```js
globalThis.global = {};
globalThis.module = {};
```
