### ISSUE TITLE
Various properties on bool exist in `dir()` but can't be accessed

### ISSUE THREAD

**Issue by 00001H** [brython-dev/brython#2527]
The properties `as_integer_ratio`, `bit_count`, `bit_length` and `to_bytes` exist in the `dir()` of `bool` objects but cannot be accessed. As a side effect this also creates incredibly confusing error messages. (This is not an issue with different Unicode characters with the same look here -- I literally copy-pasted the output from `dir()`.)
```py
>>> dir(False)
[... (snip) ..., 'as_integer_ratio', 'bit_count', 'bit_length', ... (snip) ..., 'to_bytes']
>>> False.as_integer_ratio()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bool' object has no attribute 'as_integer_ratio'. Did you mean: 'as_integer_ratio'?
>>> False.bit_count
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bool' object has no attribute 'bit_count'. Did you mean: 'bit_count'?
>>> False.bit_length
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bool' object has no attribute 'bit_length'. Did you mean: 'bit_length'?
>>> False.to_bytes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bool' object has no attribute 'to_bytes'. Did you mean: 'to_bytes'?
```

**Comment by PierreQuentel** [comment]
Thanks for this report and #2526 @00001H !
