### ISSUE TITLE
documentation website is broken

### ISSUE THREAD

**Issue by glyph** [brython-dev/brython#459]
I loaded the page in Safari and saw nothing.  Since sometimes I've reported bugs with Safari in the past and it's not the best supported browser, I tried in Firefox as well.

I clicked http://brython.info/doc/en/index.html# and then clicked on "deploying an application" to see the state of the art with brython deployment.  In the console, I see this:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help http://xhr.spec.whatwg.org/ brython.js:6823:43
"Error 404 means that Python module docs was not found at url http://brython.info/doc/en/docs.py" brython.js:6837:1
"Error 404 means that Python module docs was not found at url http://brython.info/doc/en/docs/__init__.py" brython.js:6837:1
"Error 404 means that Python module highlight was not found at url http://brython.info/doc/en/highlight.py" brython.js:6837:1
"Error 404 means that Python module highlight was not found at url http://brython.info/doc/en/highlight/__init__.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/doc/en/_locale.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/doc/en/_locale/__init__.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/src/Lib/site-packages/_locale.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/src/Lib/site-packages/_locale/__init__.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/doc/en/_locale.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/doc/en/_locale/__init__.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/src/Lib/site-packages/_locale.py" brython.js:6837:1
"Error 404 means that Python module _locale was not found at url http://brython.info/src/Lib/site-packages/_locale/__init__.py" brython.js:6837:1
pas de py_src pour docs_load_3 brython.js:6118:38
SyntaxError: missing ; before statement
Stack trace:
$BRGeneratorDict.__next__@http://brython.info/src/brython.js:10544:36
$B.make_method/method/instance_method@http://brython.info/src/brython.js:4445:8
next@http://brython.info/src/brython.js:5592:26
$StringDict.join@http://brython.info/src/brython.js:9003:23
getattr/method@http://brython.info/src/brython.js:5414:8
@http://brython.info/src/brython.js line 6917 > eval:1422:37
@http://brython.info/src/brython.js line 6917 > eval:445:32
$B.make_method/method/instance_method@http://brython.info/src/brython.js:4445:8
@http://brython.info/src/brython.js line 6917 > eval:983:51
@http://brython.info/src/brython.js line 6917 > eval:109:50
@http://brython.info/src/brython.js line 4148 > eval:23:5
run_script@http://brython.info/src/brython.js:4148:1
callback@http://brython.info/src/brython.js:4121:1
load_scripts@http://brython.info/src/brython.js:4139:1
brython@http://brython.info/src/brython.js:4244:32
onload@http://brython.info/doc/en/index.html#:1:1
 brython.js:6119:1
Javascript error TypeError: $B.$py_src[mod_name] is undefined
Stack trace:
$B.exception@http://brython.info/src/brython.js:6120:5
$B.is_exc@http://brython.info/src/brython.js:6141:34
@http://brython.info/src/brython.js line 6917 > eval:118:74
@http://brython.info/src/brython.js line 4148 > eval:23:5
run_script@http://brython.info/src/brython.js:4148:1
callback@http://brython.info/src/brython.js:4121:1
load_scripts@http://brython.info/src/brython.js:4139:1
brython@http://brython.info/src/brython.js:4244:32
onload@http://brython.info/doc/en/index.html#:1:1
 brython.js:4151:32
Error: 
_b_.RuntimeError()
 brython.js%20line%206159%20%3E%20eval:97
run_script()
 brython.js:4152
callback()
 brython.js:4121
load_scripts()
 brython.js:4139
brython()
 brython.js:4244
onload()
 index.html:1
 brython.js%20line%206159%20%3E%20eval:97:407
Traceback (most recent call last):
RuntimeError: TypeError: $B.$py_src[mod_name] is undefined brython.js:4985:47
ReferenceError: load is not defined
onclick()
 index.html:1

```

**Comment by PierreQuentel** [comment]
I get the same error message, but the documentation is at [http://brython.info/static_doc/fr/intro.html?lang=en](http://brython.info/static_doc/fr/intro.html?lang=en) ; this is where the link "documentation" in the home page leads. The pages at brython.info/doc are an old version that I should remove.

**Comment by glyph** [comment]
Please delete it then :-)

**Comment by PierreQuentel** [comment]
done !

**Comment by glyph** [comment]
Thank you 😄
