### ISSUE TITLE
None value is not coverted to null in JavaScript.

### ISSUE THREAD

**Issue by jcubic** [brython-dev/brython#696]
I don't know if this is a bug but I have code like this (that use jQuery Terminal library):
```python
from browser import window, alert

def interpreter(command, term):
    term.echo(">>> " + command)

window.jQuery("body").terminal(interpreter)
```

and I have exception in JavaScript because None value returned by interpreter is a cycle that can't be used in JSON.stringify because In jQuery Terminal the value returned by the function is processed and echoed in terminal (It can be a string or a promise). Is there a way to convert `None` to null or undefined to be used in JavaScript or return undefined/null from javascript?

I've fixed the issue by wrapping terminal function invocation and wrap interpreter with function that don't return anything, but it would be nice if Brython convert None to null in python functions.

I'm using stable version from github.

**Comment by imnvr** [comment]
"I've fixed the issue by wrapping terminal function invocation and wrap interpreter with function that don't return anything, but it would be nice if Brython convert None to null in python functions."
Nice patch but definitely would be amazing to have Brython take care of this.

**Comment by jonathanverner** [comment]
The problem is that the function being called does not know whether it is called from python (where None should be returned) or from javascript. I guess (although I haven't really thought about the corner cases) null could be returned in any case, but that would require rather invasive changes in Brython...

**Comment by PierreQuentel** [comment]
In the commit referenced above I have added 2 new constants in built-in module __javascript__, called `NULL` and `UNDEFINED`, set to Javascript values `null` and `undefined`. They can be returned by a Brython function used by a Javascript library that handles these values.

I tried this code in a page with the Terminal library : 
```python
from browser import window
import javascript

def interpreter(command, term):
    term.echo(">>> " + command)
    return javascript.UNDEFINED

window.jQuery("body").terminal(interpreter)
```

I don't know if the program does what is expected, but at least it doesn't crash ;-)

Does this help ?

**Comment by jcubic** [comment]
It's promising, I've updated my pen it execute python code but throw exception:

```
[USER]: 
Error
    at Object._b_.NameError (eval at $make_exc (https://rawgit.com/brython-dev/brython/master/www/src/brython.js:6499:1), <anonymous>:73:376)
    at Object.$B.$global_search (https://rawgit.com/brython-dev/brython/master/www/src/brython.js:4901:11)
    at r.fn.init.interpreter2 (eval at run_script (https://rawgit.com/brython-dev/brython/master/www/src/brython.js:4198:1), <anonymous>:179:35)
    at r.fn.init.<anonymous> (https://rawgit.com/brython-dev/brython/master/www/src/brython.js:7042:14)
    at r.fn.init.<anonymous> (https://rawgit.com/brython-dev/brython/master/www/src/brython.js:7042:14)
    at Object.commands (https://rawgit.com/jcubic/jquery.terminal/devel/js/jquery.terminal.js:4768:58)
    at Object.ENTER (https://rawgit.com/jcubic/jquery.terminal/devel/js/jquery.terminal.js:1211:29)
    at HTMLHtmlElement.keydown_event (https://rawgit.com/jcubic/jquery.terminal/devel/js/jquery.terminal.js:2316:41)
    at HTMLHtmlElement.dispatch (https://code.jquery.com/jquery-3.1.1.min.js:3:10315)
    at HTMLHtmlElement.q.handle (https://code.jquery.com/jquery-3.1.1.min.js:3:8342)
```

You can take a look here: https://codepen.io/jcubic/pen/QqJxqZ

**Comment by jcubic** [comment]
Oh, I've forget about import javascript, it work fine thanks. too bad you can do that automatically but that is also not that bad.

**Comment by PierreQuentel** [comment]
As Jonathan said, it's not possible for a function to know if it's called from Brython or Javascript. And anyway, there must be a way to return either `null` or `undefined` (I saw that jQuery Terminal doesn't handle these values the same way).

Can the issue be closed ?
