### ISSUE TITLE
`python -m brython --install` fails with FileNotFoundError: demo.html

### ISSUE THREAD

**Issue by mshenfield** [brython-dev/brython#796]
I get an error following the [installation docs](http://brython.info/static_doc/en/install.html) and installing brython locally.  Output here:

```
Installing Brython in an empty directory
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/me/.local/share/virtualenvs/shoppy-LHEnuaYn/src/brython/setup/brython.py", line 81, in <module>
    shutil.copyfile(os.path.join(src_path, path), path)
  File "/Users/me/.local/share/virtualenvs/shoppy-LHEnuaYn/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mshenfield/.local/share/virtualenvs/shoppy-LHEnuaYn/src/brython/setup/data/demo.html'
```

I'm installing inside of a [`pipenv`](http://docs.pipenv.org/).  It looks like `demo.html` was removed in [this commit](a04ba55ea001cf00dbd54f0fd009743c20f783cc).

**Versions**
Python 2.7
`brython` 3.5.0rc1

**Comment by mshenfield** [comment]
The problem is that I'm installing directly from a checked out repository.  Works fine from `pip install brython`.
