### ISSUE TITLE
SyntaxError when building brython_modules.js & importing from browser.template

### ISSUE THREAD

**Issue by benjaminrigaud** [brython-dev/brython#812]
Hello,

I have a simple html file

```html
<html>
<head>
    <script src="brython.js"></script>
    <script src="brython_stdlib.js"></script>
</head>
<body onload="brython(10)">
	<script type="text/python">
		from browser.template import Template
		print(Template)
	</script>
</body>
</html>

```

```
python -m brython --modules
Create brython_modules.js with all the modules used by the application
searching brython_stdlib.js...
finding packages...
syntax error .../brython-issue/main.html
```

Is that possible to have more details about the syntax error?

Moreover, I saw an error about the traceback module when trying to include the generated (but incomplete?) modules file into the html.

Ben

**Comment by PierreQuentel** [comment]
Bonjour Benjamin,

I could not reproduce the bug with the content of this html page, there is no syntax error in the Python script.

In the commit referenced above I have added a full Python traceback in case of syntax error. You can test it by cloning the repository, then run "`python setup.py sdist`" and "`python setup.py install`" in the __setup__ directory, and then run again "`python -m brython --modules`"

**Comment by benjaminrigaud** [comment]
Bonjour Pierre :)

Thank you, I'll give it a go ASAP!

**Comment by benjaminrigaud** [comment]
Ok. My local python is 3.5.2 and doesn't support f-strings :)

```bash
python -m brython --modules
Create brython_modules.js with all the modules used by the application
searching brython_stdlib.js...
finding packages...
syntax error /home/.../brython-issue/main.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 292, in get_imports
    imports = self.get_imports(module_dict[module][1])
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 308
    raise TemplateError(f"wrong binding: {binding}")
                                                  ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 10
    txt = document.createTextNode(f" {nb}")
                                         ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9
    element <= html.B(f" {nb}")
                             ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 11
    ul.insertBefore(html.LI(f"element before {nb}"), element)
                                                 ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 11
    ul.insertBefore(html.LI(f"element after {nb}"), element.nextSibling)
                                                ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9
    table <= TR(TH(f"Column {i}") for i in range(5))
                               ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 11
    dropdown = html.SELECT(html.OPTION(f"Choice {i}") for i in range(5))
                                                   ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 10
    document["zone16"] <= (f"Value in INPUT field: {input}",
                                                          ^
SyntaxError: invalid syntax
syntax error /home/.../brython-issue/demo.html
Traceback (most recent call last):
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 339, in inspect
    self.get_imports(script)
  File "/home/.../.local/share/virtualenvs/brython-issue/lib/python3.5/site-packages/brython-3.5.2-py3.5.egg/list_modules.py", line 282, in get_imports
    tree = ast.parse(src)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 9
    moving.style.transform = f"rotate({angle}deg)"
                                                 ^
SyntaxError: invalid syntax
```
I'll update to 3.6.X

**Comment by benjaminrigaud** [comment]
As some parts of Brython requires Python 3.6 (server-side), It may be a good idea to check the version in setup.py

We may want to document that requirement too in the `Local install` section.
