### ISSUE TITLE
Regression in strftime()

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#943]
This test from www/tests/test_datetime.py is failing:

```python
from datetime import date
d = date(2010, 9, 7)
assert "Tested on {0:%Y-%m-%d}".format(d) == "Tested on 2010-09-07"
```

```
Traceback (most recent call last):
  File "VFS.browser.timer.py", line 8, in f
    return func(*args,**kw)
  File "VFS.asyncio.events.py", line 70, in _step
    callback()
  File "VFS.asyncio.events.py", line 177, in _step
    callback(*args)
  File "VFS.asyncio.coroutines.py", line 62, in _step
    f=self._coro_obj.send(val)
  File "http://localhost:8001/tests//tests", line 33, in run0
    state, t0, t1, _ = utils.run(src)
  File "http://localhost:8001/tests/brython_test_utils/__init__.py", line 84, in run
    exec(src, ns)
  File "<string>", line 3, in <module>
  File "VFS.datetime.py", line 902, in __format__
    return self.strftime(fmt)
  File "VFS.datetime.py", line 896, in strftime
    return _wrap_strftime(self,fmt,self.timetuple())
  File "VFS.datetime.py", line 256, in _wrap_strftime
    return _time.strftime(newformat,timetuple)
  File "VFS.time.py", line 283, in strftime
    c_format=formatter("x")+" "+formatter("X")
ValueError: no format x for locale en-US
```

**Comment by schmave** [comment]
Great!
