### ISSUE TITLE
Calling exec at the global level overwrites the stack

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#958]
Run this code in the editor https://brython.info/tests:

```python
import traceback as tb

try:
    exec('def f(): return 1/0\nf()')
except ZeroDivisionError:
    tb.print_exc()
```

This is printed:
```
Traceback (most recent call last):
  File "VFS.browser.timer.py", line 8, in f
    return func(*args,**kw)
  File "VFS.asyncio.events.py", line 70, in _step
    callback()
  File "VFS.asyncio.events.py", line 177, in _step
    callback(*args)
  File "VFS.asyncio.coroutines.py", line 62, in _step
    f=self._coro_obj.send(val)
  File "http://localhost:8001/tests//tests", line 33, in run0
    state, t0, t1, _ = utils.run(src)
  File "http://localhost:8001/tests/brython_test_utils/__init__.py", line 84, in run
    exec(src, ns)
  File "<string>", line 2, in <module>
  File "<string>", line 2, in <module>
  File "<string>", line 1, in f
ZeroDivisionError: division by zero
```

`File "<string>", line 2, in <module>` appears twice, which is incorrect. The first instance should instead be `File "<string>", line 4, in <module>`. It seems that modifying `$locals.$line_info` within the exec modifies the line info in `$B.frames_stack`.

This is similar to issue #887.

**Comment by PierreQuentel** [comment]
@schmave 
Thanks for this report - getting the same errors as in CPython is a nightmare...
Since the scripts in the editor at tests/index.html are run in an `exec()`, the source code is not available. I have added a specific test page for exception tracebacks, it is executed by hitting the button "Test exceptions".
I think the result is now ok for this issue, so I close it.

**Comment by schmave** [comment]
@PierreQuentel Yes this looks good now with your fixes. That's a great idea to move the traceback tests to their own file. Thanks for resurrecting them.
